### ISSUE TITLE
Unknown server-error when launching the app

### ISSUE THREAD

**Issue by joaozanutto** [appium-userland/appium-flutter-driver#144]
So, I'm trying to run this simple test that I've built last week (in which it was working) and now I'm receiving this unknown error below. The project is not much different than the boilerplate project, just adapted to my APP. The APP opens up in my device and stops after 3 retries.

```
WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
2021-02-15T11:26:32.444Z INFO webdriver: Retrying 3/3
2021-02-15T11:26:32.444Z INFO webdriver: [POST] http://localhost:4723/wd/hub/session
2021-02-15T11:26:32.445Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      platformName: 'Android',
      platformVersion: '10',
      deviceName: 'Emulator',
      app: '/home/jpberno/appium_test/helpers/target_apps/app-qa-debug.apk',
      automationName: 'Flutter',
      retryBackoffTime: 500
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    platformName: 'Android',
    platformVersion: '10',
    deviceName: 'Emulator',
    app: '/home/jpberno/appium_test/helpers/target_apps/app-qa-debug.apk',
    automationName: 'Flutter',
    retryBackoffTime: 500
  }
}
2021-02-15T11:26:45.473Z ERROR webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
2021-02-15T11:26:45.473Z ERROR webdriver: unknown error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at Object.getErrorFromResponseBody (/home/jpberno/appium_test/helpers/target_apps/node_modules/webdriver/build/utils.js:94:12)
    at WebDriverRequest._request (/home/jpberno/appium_test/helpers/target_apps/node_modules/webdriver/build/request.js:134:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.startWebDriverSession (/home/jpberno/appium_test/helpers/target_apps/node_modules/webdriver/build/utils.js:29:20)
    at async Function.newSession (/home/jpberno/appium_test/helpers/target_apps/node_modules/webdriver/build/index.js:35:45)
    at async Object.exports.remote (/home/jpberno/appium_test/helpers/target_apps/node_modules/webdriverio/build/index.js:53:22)
    at async /home/jpberno/appium_test/helpers/target_apps/index.js:21:17
(node:20034) UnhandledPromiseRejectionWarning: Error: Failed to create session.
An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at Object.startWebDriverSession (/home/jpberno/appium_test/helpers/target_apps/node_modules/webdriver/build/utils.js:34:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function.newSession (/home/jpberno/appium_test/helpers/target_apps/node_modules/webdriver/build/index.js:35:45)
    at async Object.exports.remote (/home/jpberno/appium_test/helpers/target_apps/node_modules/webdriverio/build/index.js:53:22)
    at async /home/jpberno/appium_test/helpers/target_apps/index.js:21:17
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20034) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20034) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I also checked `http://127.0.0.1:4723/wd/hub/sessions` via chrome browser and I see this result:
`{"value":[],"sessionId":null,"status":0}`

Not sure what more info should I provide. Thank you in advance

**Comment by KazuCocoa** [comment]
How was your logcat while the test running?
Probably you can find a line like `Observatory listening on xxx`. Only then this driver can work.

**Comment by vishchi** [comment]
Change the platform version to that of yours.

**Comment by KazuCocoa** [comment]
Please try out the latest version with appium 2
