### ISSUE TITLE
Vertical scroll to element until it's visible is failing with "Error: [object Object] is not a valid options" exception

### ISSUE THREAD

**Issue by okaruk** [appium-userland/appium-flutter-driver#172]
While performing vertical scroll to element until it's visible getting the following error:

```
[HTTP] --> POST /wd/hub/session/acf4933c-8840-4e98-b3e0-c958b8064e8a/execute
[HTTP] {"script":"flutter:scrollUntilVisible","args":[{"ELEMENT":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoidHJhY3Rvcl9mb3JtX2xpc3RfdmlldyIsImtleVZhbHVlVHlwZSI6IlN0cmluZyJ9"},{"item":{"ELEMENT":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiU1VCTUlUIFRSQUNUT1IgSU5GT1JNQVRJT04iLCJrZXlWYWx1ZVR5cGUiOiJTdHJpbmcifQ=="},"dyScroll":-256}]}
[debug] [MJSONWP (acf4933c)] Calling AppiumDriver.execute() with args: ["flutter:scrollUntilVisible",[{"ELEMENT":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoidHJhY3Rvcl9mb3JtX2xpc3RfdmlldyIsImtleVZhbHVlVHlwZSI6IlN0cmluZyJ9"},{"item":{"ELEMENT":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiU1VCTUlUIFRSQUNUT1IgSU5GT1JNQVRJT04iLCJrZXlWYWx1ZVR5cGUiOiJTdHJpbmcifQ=="},"dyScroll":-256}],"acf4933c-8840-4e98-b3e0-c958b8064e8a"]
[debug] [FlutterDriver] Executing Flutter driver command 'execute'
[debug] [MJSONWP (acf4933c)] Encountered internal error running command: Error: [object Object] is not a valid options
[debug] [MJSONWP (acf4933c)]     at Object.exports.scrollUntilVisible (/Users/okaruk/.nvm/versions/node/v14.13.0/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/commands/execute/scroll.ts:91:11)
[debug] [MJSONWP (acf4933c)]     at FlutterDriver.exports.execute (/Users/okaruk/.nvm/versions/node/v14.13.0/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/commands/execute.ts:48:14)
[debug] [MJSONWP (acf4933c)]     at commandExecutor (/Users/okaruk/.nvm/versions/node/v14.13.0/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/appium-base-driver/lib/basedriver/driver.js:330:9)
[debug] [MJSONWP (acf4933c)]     at /Users/okaruk/.nvm/versions/node/v14.13.0/lib/node_modules/appium/node_modules/async-lock/lib/index.js:125:12
[debug] [MJSONWP (acf4933c)]     at AsyncLock._promiseTry (/Users/okaruk/.nvm/versions/node/v14.13.0/lib/node_modules/appium/node_modules/async-lock/lib/index.js:249:31)
[debug] [MJSONWP (acf4933c)]     at exec (/Users/okaruk/.nvm/versions/node/v14.13.0/lib/node_modules/appium/node_modules/async-lock/lib/index.js:124:9)
[debug] [MJSONWP (acf4933c)]     at AsyncLock.acquire (/Users/okaruk/.nvm/versions/node/v14.13.0/lib/node_modules/appium/node_modules/async-lock/lib/index.js:140:3)
[debug] [MJSONWP (acf4933c)]     at FlutterDriver.executeCommand (/Users/okaruk/.nvm/versions/node/v14.13.0/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/appium-base-driver/lib/basedriver/driver.js:343:39)
[debug] [MJSONWP (acf4933c)]     at FlutterDriver.executeCommand (/Users/okaruk/.nvm/versions/node/v14.13.0/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/driver.ts:122:22)
[debug] [MJSONWP (acf4933c)]     at AppiumDriver.executeCommand (/Users/okaruk/.nvm/versions/node/v14.13.0/lib/node_modules/appium/lib/appium.js:532:36)
[debug] [MJSONWP (acf4933c)]     at runMicrotasks (<anonymous>)
[debug] [MJSONWP (acf4933c)]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[debug] [MJSONWP (acf4933c)]     at asyncHandler (/Users/okaruk/.nvm/versions/node/v14.13.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:300:21)
[HTTP] <-- POST /wd/hub/session/acf4933c-8840-4e98-b3e0-c958b8064e8a/execute 500 2 ms - 209
[HTTP]  
```

Here is complete command written on Ruby:
`driver.execute_script('flutter:scrollUntilVisible', by_type('ListView'), {item: by_value_key('submit_btn'), dyScroll: -256})
`

It should be okay to skip `dxScroll` value as per Flutter docs - **At least one of `dxScroll` and `dyScroll` must be non-zero.** (https://api.flutter.dev/flutter/flutter_driver/FlutterDriver/scrollUntilVisible.html)

Probably there is a reason of the fail: https://github.com/truongsinh/appium-flutter-driver/blob/master/driver/lib/commands/execute/scroll.ts#L89 
I suppose the condition should look like: `if (dxScroll === 0 && dyScroll === 0)`, to not to throw exception when at least one value equals zero

**Comment by okaruk** [comment]
@savy-91 @KazuCocoa is it possible to fix this issue in the same way you did for `scroll` to allow the horizontal or vertical scroll to element until its visible?

_PR:_ https://github.com/appium-userland/appium-flutter-driver/pull/205/files

**Comment by KazuCocoa** [comment]
Could be. You can try it out with flutter-driver v0.0.33

**Comment by savy-91** [comment]
@okaruk I created a new PR that should fix your error, you can try it here: https://github.com/savy-91/appium-flutter-driver/tree/fix/scroll_until_visible
