### ISSUE TITLE
Error trying to use FlutterElement  with Python: TypeError: argument of type 'FlutterElement' is not iterable

### ISSUE THREAD

**Issue by igortavtib** [appium-userland/appium-flutter-driver#197]
Trying to use Flutter finder with python I get the following error: 
`/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    driver.execute('flutter::waitFor', input_element)
  File "/home/igortavtib/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 315, in execute
    elif 'sessionId' not in params:
TypeError: argument of type 'FlutterElement' is not iterable`

 I was trying to run a simple test to use de package with the following code:

```python
from appium.webdriver import Remote
from appium_flutter_finder import FlutterElement, FlutterFinder

driver = Remote('http://localhost:4723/wd/hub', dict(
    platformName='android',
    automationName='flutter',
    udid='emulator-5554',
    app='/home/igortavtib/Projects/test/app.apk'
))

finder = FlutterFinder()

key_finder = finder.by_value_key('input-user')
input_element = FlutterElement(driver, key_finder)
driver.execute('flutter::waitFor', input_element)
input_element.send_keys('Teste 123')

```
  Did I do something wrong?

**Comment by KazuCocoa** [comment]
Could you share the full appium log?

**Comment by igortavtib** [comment]
Shure, it seens there is no error in the appium log
```
[debug] [ADB] Running '/home/igortavtib/Android/sdk/platform-tools/adb -P 5037 start-server'
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices
[debug] [ADB] Connected devices: [{"udid":"emulator-5554","state":"device"}]
[AndroidDriver] Using device: emulator-5554
[debug] [FlutterDriver] /home/igortavtib/Android/sdk/platform-tools/adb -s emulator-5554 forward tcp:42309 tcp:42309
[FlutterDriver] Attempt #1
[FlutterDriver] Connecting to Dart Observatory: ws://127.0.0.1:42309/pSki7r6a518=/ws
[FlutterDriver] Connected to ws://127.0.0.1:42309/pSki7r6a518=/ws
[FlutterDriver] Listing all isolates: [{"type":"@Isolate","id":"isolates/3888104384679223","name":"main","number":"3888104384679223","isSystemIsolate":false}]
[FlutterDriver] "ext.flutter.driver" is not found in "extensionRPCs" ["ext.ui.window.scheduleFrame","ext.dart.io.getHttpEnableTimelineLogging","ext.dart.io.setHttpEnableTimelineLogging","ext.dart.io.getSocketProfile","ext.dart.io.startSocketProfiling","ext.dart.io.pauseSocketProfiling","ext.dart.io.clearSocketProfile","ext.dart.io.getVersion"]
[FlutterDriver] Waiting 3 seconds before trying...
[FlutterDriver] Attempt #2
[FlutterDriver] Connecting to Dart Observatory: ws://127.0.0.1:42309/pSki7r6a518=/ws
[FlutterDriver] Connected to ws://127.0.0.1:42309/pSki7r6a518=/ws
[FlutterDriver] Listing all isolates: [{"type":"@Isolate","id":"isolates/3888104384679223","name":"main","number":"3888104384679223","isSystemIsolate":false}]
[Appium] New FlutterDriver session created successfully, session 6ff930d9-a5f2-45cf-8b43-f9fba8eb3993 added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1635613251046 (14:00:51 GMT-0300 (Brasilia Standard Time))
[debug] [W3C (6ff930d9)] Cached the protocol value 'W3C' for the new session 6ff930d9-a5f2-45cf-8b43-f9fba8eb3993
[debug] [W3C (6ff930d9)] Responding to client with driver.createSession() result: {"capabilities":{"allowCors":false,"reboot":false,"ipa":null,"address":"0.0.0.0","port":4723,"basePath":"/wd/hub","keepAliveTimeout":null,"callbackAddress":null,"callbackPort":null,"bootstrapPort":4724,"backendRetries":3,"sessionOverride":false,"launch":false,"logFile":null,"loglevel":"debug","logTimestamp":false,"localTimezone":false,"logNoColors":false,"webhook":null,"safari":false,"defaultDevice":false,"forceIphone":false,"forceIpad":false,"automationTraceTemplatePath":null,"instrumentsPath":null,"nodeconfig":null,"robotAddress":"0.0.0.0","robotPort":-1,"chromedriverExecutable":null,"showConfig":false,"noPermsCheck":false,"enforceStrictCaps":false,"isolateSimDevice":false,"tmpDir":"/tmp","traceDir":null,"debugLogSpacing":false,"suppressKillServer":false,"longStacktrace":false,"webkitDebugProxyPort":27753,"wdaLocalPort":8100,"defaultCapabilities":{},"relaxedSecurityEnabled":false,"allowInsecure":[],"denyInsecure":[],"defaultCommandTimeout":60,"keepArtifacts":false,"platformName":"android","platformVersio...
[HTTP] <-- POST /wd/hub/session 200 16250 ms - 2057
[HTTP] 
[BaseDriver] Shutting down because we waited 60 seconds for a command
[Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session '6ff930d9-a5f2-45cf-8b43-f9fba8eb3993' from our master session list
[debug] [FlutterDriver] Deleting Flutter Driver session
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [WD Proxy] Matched '/' to command name 'deleteSession'
[debug] [WD Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:8200/wd/hub/session/2b12c74a-af6c-4ece-9f00-e60bd92a2869] with no body
[debug] [WD Proxy] Got response with status 200: {"sessionId":"2b12c74a-af6c-4ece-9f00-e60bd92a2869","value":null}
[debug] [ADB] Running '/home/igortavtib/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop com.crewchief.crewchiefMobile'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200 
[debug] [ADB] Running '/home/igortavtib/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp:8200'
[UiAutomator2] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running '/home/igortavtib/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[FlutterDriver] Connection to ws://127.0.0.1:42309/pSki7r6a518=/ws closed
[FlutterDriver] Connection to ws://127.0.0.1:42309/pSki7r6a518=/ws closed
[debug] [Instrumentation] .
[debug] [Instrumentation] Time: 70.188
[debug] [Instrumentation] 
[debug] [Instrumentation] OK (1 test)
[debug] [Instrumentation] The process has exited with code 0
```

**Comment by igortavtib** [comment]
@KazuCocoa I've seen there was a pull request for the python FlutterFinder, is this related to this topic? I can make a fork and help to test the solution

**Comment by KazuCocoa** [comment]
No. My PR is for Appium Python client v2.0 stuff.

I noticed you called `driver.execute('flutter::waitFor', input_element)`, but `driver.execute_script` was expected command for Python.


https://github.com/appium-userland/appium-flutter-driver#commands
> The below WebDriver example is by webdriverio. flutter: prefix commands are mobile: command in appium for Android and iOS. Please replace them properly with your client.

https://appium.io/docs/en/commands/mobile-command/ is the mobile: command's link. It has an example for each client.

**Comment by KazuCocoa** [comment]
btw, i've added https://github.com/appium-userland/appium-flutter-driver/blob/master/example/python/example.py#L33 as an example
