### ISSUE TITLE
How to validate Input InputDecoration in Flutter Driver

### ISSUE THREAD

**Issue by litan1984** [appium-userland/appium-flutter-driver#240]
decoration: InputDecoration(
                  labelText: "test lebel text",
                  errorText: _test error text,

**Comment by KazuCocoa** [comment]
Get the text field by `byType` finder + get the element text by `getText`? Then, you can check the input text on your client side.

**Comment by YudhiPTGue** [comment]
i cannot getText() btw, anyone can help ? this error could be like this : 

`org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot execute command get_text, server reponse {
  "isError": true,
  "response": "Uncaught extension error while executing get_text: Unsupported operation: Type GSRoundedButton is currently not supported by getText\n#0      CommandHandlerFactory._getText (package:flutter_driver/src/common/handler_factory.dart:418:7)\n<asynchronous suspension>\n#1      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:372:31)\n<asynchronous suspension>\n#2      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:855:18)\n<asynchronous suspension>\n",
  "type": "_extensionType",
  "method": "ext.flutter.driver"
}
Build info: version: '4.8.0', revision: '267030adea'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '12.5', java.version: '11.0.17'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [2696f06d-938f-436e-8cf5-730a0180d0a0, getElementText {id=eyJrZXlWYWx1ZVR5cGUiOiJTdHJpbmciLCJrZXlWYWx1ZVN0cmluZyI6IkJ1dHRvbk1hc3VrUmVnaXN0ZXJQaG9uZSIsImZpbmRlclR5cGUiOiJCeVZhbHVlS2V5In0=}]
Capabilities {appium:address: 0.0.0.0, appium:allowCors: false, appium:allowInsecure: [], appium:app: /Users/ge00000718/Downloads..., appium:automationName: Flutter, appium:basePath: , appium:callbackPort: 4723, appium:debugLogSpacing: false, appium:denyInsecure: [], appium:deviceName: emulator-5554, appium:driver: {xcuitest: {wdaLocalPort: 8100}}, appium:extraArgs: [], appium:fastReset: true, appium:keepAliveTimeout: 600, appium:localTimezone: false, appium:logNoColors: false, appium:logTimestamp: false, appium:loglevel: debug, appium:longStacktrace: false, appium:noPermsCheck: false, appium:port: 4723, appium:relaxedSecurityEnabled: false, appium:sessionOverride: false, appium:skipUninstall: true, appium:strictCaps: false, appium:subcommand: server, appium:tmpDir: /var/folders/8s/rg1hmz11385..., appium:useDrivers: [], appium:usePlugins: [], platformName: ANDROID}
Element: [org.example.FlutterElement@2155bd07 -> unknown locator]
`
