### ISSUE TITLE
the application is closed after it is launched

### ISSUE THREAD

**Issue by AhmedBahgat** [appium-userland/appium-flutter-driver#241]
I can find elements by flutter driver, but only in case of Debug, when I run it just start the application and close it in few seconds before it is full loaded. 

I added `flutter:waitFor` but it throw this exception 

```
[0-0]   script: 'flutter:waitFor',
[0-0]   args: [
[0-0]     'eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiZGViaXRCdXR0b24iLCJrZXlWYWx1ZVR5cGUiOiJTdHJpbmcifQ'
[0-0]   ]
[0-0] }
[0-0] 2022-01-26T10:49:01.741Z ERROR webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: Cannot execute command waitFor, server reponse {
[0-0]   "isError": true,
[0-0]   "response": "Uncaught extension error while executing waitFor: 'package:flutter_driver/src/extension/extension.dart': Failed assertion: line 367 pos 14: 'WidgetsBinding.instance!.isRootWidgetAttached || !command.requiresRootWidgetAttached': No root widget is attached; have you remembered to call runApp()?\n#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:47:61)\n#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)\n#2      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:367:14)\n#3      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:602:32)\n<asynchronous suspension>\n",
[0-0]   "type": "_extensionType",
[0-0]   "method": "ext.flutter.driver"
[0-0] }
[0-0] unknown error in "My Login application.login with another credential"
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot execute command waitFor, server reponse {
  "isError": true,
  "response": "Uncaught extension error while executing waitFor: 'package:flutter_driver/src/extension/extension.dart': Failed assertion: line 367 pos 14: 'WidgetsBinding.instance!.isRootWidgetAttached || !command.requiresRootWidgetAttached': No root widget is attached; have you remembered to call runApp()?\n#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:47:61)\n#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)\n#2      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:367:14)\n#3      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:602:32)\n<asynchronous suspension>\n",
  "type": "_extensionType",
  "method": "ext.flutter.driver"
}
    at getResponseForW3CError (/Users//repo/wdio/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/Users//repo/wdio/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)
```

Is there a way to wait till the appActivity is loaded? 

I could do workaround to increase   `connectionRetryCount` to 100 to have enough time to keep retrying. Is there a configuration for time interval between retries ?

**Comment by KazuCocoa** [comment]
Do you mean https://github.com/appium-userland/appium-flutter-driver/blob/3eac68ffc7bf6f27cff0eeea11a6ceadfb2b9a81/driver/lib/sessions/observatory.ts#L12 to 100?
No, for now, but we can add it in case an app needs more time to load the app to launch.

**Comment by AhmedBahgat** [comment]
@KazuCocoa 
it doesn't use this parameter. it is relay on webdriverIO parameters `connectionRetryCount`

**Comment by AhmedBahgat** [comment]
@KazuCocoa 
another question please.

with Wdio v7 I don't need to add this `const driver = await wdio.remote(opts);` because it will be initialised by default once I set the `'appium:automationName': 'Flutter',` right?

**Comment by KazuCocoa** [comment]
Sorry do you mean how to use `connectionRetryCount`? I haven't used flutter driver via webdriverio. So i don't know well its internal.

**Comment by KazuCocoa** [comment]
>  it doesn't use this parameter. it is relay on webdriverIO parameters connectionRetryCount

Then, I guess webdriverio itself needs to wait longer than the default preference. it sounds like it is not this driver itself.
