### ISSUE TITLE
can't launch ios app on browserstack using appium flutter driver

### ISSUE THREAD

**Issue by drkhannah** [appium-userland/appium-flutter-driver#253]
browserstack has told me that i need to build my ios app in --profile mode, which is also true of your documentation

the problem is that even if i build in --profile mode, they only way i can archive a .ipa is to choose the Release scheme, choosing any other scheme causes the archive to fail.

running this command to build in profile mode makes the build succeed

`[08:09:30]: $ flutter build ios --profile --build-number\=776 --build-name\=5.0.776 --no-codesign --flavor Profile -t lib/test_main.dart
`

then i archive the .ipa using the xcode Release scheme, the archive succeeds.

I upload to browserstack app live

then i run my appium tests but i get this error 

```
[0-0] 2022-02-22T13:17:27.447Z INFO webdriver: Retrying 3/3
[0-0] 2022-02-22T13:17:27.447Z INFO webdriver: [POST] https://hub-cloud.browserstack.com/wd/hub/session
[0-0] 2022-02-22T13:17:27.448Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       app: 'REDACTED',
[0-0]       device: 'iPhone 12',
[0-0]       os_version: '14.0',
[0-0]       project: 'Baird Mobile',
[0-0]       build: 'browserstack-build-ios',
[0-0]       name: 'Tests',
[0-0]       automationName: 'Flutter',
[0-0]       acceptSslCerts: 'true'
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     app: 'REDACTED',
[0-0]     device: 'iPhone 12',
[0-0]     os_version: '14.0',
[0-0]     project: 'Baird Mobile',
[0-0]     build: 'browserstack-build-ios',
[0-0]     name: 'Tests',
[0-0]     automationName: 'Flutter',
[0-0]     acceptSslCerts: 'true'
[0-0]   }
[0-0] }
[0-0] 2022-02-22T13:18:35.834Z ERROR webdriver: Request failed with status 200 due to WebDriver Error: Could not start Mobile Browser. Error occured while starting the session. To verify if all the pre-requisites for running Appium Flutter Driver tests have been met, refer to - https://www.browserstack.com/docs/app-automate/appium/test-hybrid-apps/test-flutter-apps
[0-0]  Reason: 
[0-0] An unknown server-side error occurred while processing the command. Original error: Failed to connect 3 times. Aborting.
[0-0] 2022-02-22T13:18:35.834Z ERROR webdriver: WebDriver Error: Could not start Mobile Browser. Error occured while starting the session. To verify if all the pre-requisites for running Appium Flutter Driver tests have been met, refer to - https://www.browserstack.com/docs/app-automate/appium/test-hybrid-apps/test-flutter-apps
[0-0]  Reason: 
[0-0] An unknown server-side error occurred while processing the command. Original error: Failed to connect 3 times. Aborting.
[0-0]     at getErrorFromResponseBody (/Users/dhannah/Development/BolUiTestFramework/node_modules/webdriver/build/utils.js:197:12)
[0-0]     at NodeJSRequest._request (/Users/dhannah/Development/BolUiTestFramework/node_modules/webdriver/build/request/index.js:158:60)
[0-0]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[0-0]     at async startWebDriverSession (/Users/dhannah/Development/BolUiTestFramework/node_modules/webdriver/build/utils.js:67:20)
[0-0]     at async Function.newSession (/Users/dhannah/Development/BolUiTestFramework/node_modules/webdriver/build/index.js:58:45)
[0-0]     at async remote (/Users/dhannah/Development/BolUiTestFramework/node_modules/webdriverio/build/index.js:73:22)
[0-0]     at async Runner._startSession (/Users/dhannah/Development/BolUiTestFramework/node_modules/@wdio/runner/build/index.js:223:56)
[0-0]     at async Runner._initSession (/Users/dhannah/Development/BolUiTestFramework/node_modules/@wdio/runner/build/index.js:176:25)
[0-0]     at async Runner.run (/Users/dhannah/Development/BolUiTestFramework/node_modules/@wdio/runner/build/index.js:88:19)
[0-0] 2022-02-22T13:18:35.835Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] Could not start Mobile Browser. Error occured while starting the session. To verify if all the pre-requisites for running Appium Flutter Driver tests have been met, refer to - https://www.browserstack.com/docs/app-automate/appium/test-hybrid-apps/test-flutter-apps
[0-0]  Reason: 
[0-0] An unknown server-side error occurred while processing the command. Original error: Failed to connect 3 times. Aborting.
[0-0]     at startWebDriverSession (/Users/dhannah/Development/BolUiTestFramework/node_modules/webdriver/build/utils.js:72:15)
[0-0]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[0-0]     at async Function.newSession (/Users/dhannah/Development/BolUiTestFramework/node_modules/webdriver/build/index.js:58:45)
[0-0]     at async remote (/Users/dhannah/Development/BolUiTestFramework/node_modules/webdriverio/build/index.js:73:22)
[0-0]     at async Runner._startSession (/Users/dhannah/Development/BolUiTestFramework/node_modules/@wdio/runner/build/index.js:223:56)
[0-0]     at async Runner._initSession (/Users/dhannah/Development/BolUiTestFramework/node_modules/@wdio/runner/build/index.js:176:25)
[0-0]     at async Runner.run (/Users/dhannah/Development/BolUiTestFramework/node_modules/@wdio/runner/build/index.js:88:19)
[0-0] FAILED in joshuarufer_jXfqM5/BairdMobile - /src/specs/login_tests.js
2022-02-22T13:18:35.948Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:03:58 

2022-02-22T13:18:35.950Z INFO @wdio/local-runner: Shutting down spawned worker
2022-02-22T13:18:36.202Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2022-02-22T13:18:36.203Z INFO @wdio/local-runner: shutting down

**Comment by drkhannah** [comment]
this is my appium version 

`appium@1.22.2 | Apache-2.0 | deps: 32 | versions: 346`

**Comment by KazuCocoa** [comment]
It seems like it is better to ask their support team first
