### ISSUE TITLE
 selenium.common.exceptions.WebDriverException: Message: Method is not implemented

### ISSUE THREAD

**Issue by M1qa** [appium-userland/appium-flutter-driver#260]
@truongsinh My code like this.An error is reported when self.driver.execute_script('flutter:waitFor', waitforfind, timeout) is executed.And the error message is selenium.common.exceptions.WebDriverException: Message: Method is not implemented.Can youhelp me?
    def isExist(self, loc, timeout=10):
        waitforfind = self.finder.by_value_key(loc)
        try:
            self.driver.execute_script('flutter:waitFor', waitforfind, timeout)
            return True
        except Exception:
            exType, exValue, exTrace = sys.exc_info()
            if 'TimeoutException' in repr(exValue):
                return False
            else:
                raise

**Comment by KazuCocoa** [comment]
Could you share the appium server log?

**Comment by M1qa** [comment]
@KazuCocoa This is the appium log.
[2022-03-07 03:22:21][HTTP] <-- POST /wd/hub/session/641053f0-4837-4327-b2e1-70e1179f7591/element 500 102 ms - 164
[2022-03-07 03:22:21][HTTP] 
[2022-03-07 03:22:27][HTTP] --> POST /wd/hub/session/641053f0-4837-4327-b2e1-70e1179f7591/execute
[2022-03-07 03:22:27][HTTP] {"script":"flutter:waitFor","args":["eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiQ0pIWSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyJ9",10],"sessionId":"641053f0-4837-4327-b2e1-70e1179f7591"}
[2022-03-07 03:22:27][MJSONWP (641053f0)] Calling AppiumDriver.execute() with args: ["flutter:waitFor",["eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiQ0pIWSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyJ9",10],"641053f0-4837-4327-b2e1-70e1179f7591"]
[2022-03-07 03:22:27][FlutterDriver] Executing proxied driver command 'execute'
[2022-03-07 03:22:27][MJSONWP (641053f0)] Encountered internal error running command: NotImplementedError: Method is not implemented
[2022-03-07 03:22:27][MJSONWP (641053f0)]     at AndroidUiautomator2Driver.execute (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\commands\execute.js:14:11)
[2022-03-07 03:22:27][MJSONWP (641053f0)]     at commandExecutor (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:335:9)
[2022-03-07 03:22:27][MJSONWP (641053f0)]     at C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\async-lock\lib\index.js:137:12
[2022-03-07 03:22:27][MJSONWP (641053f0)]     at AsyncLock._promiseTry (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\async-lock\lib\index.js:261:31)
[2022-03-07 03:22:27][MJSONWP (641053f0)]     at exec (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\async-lock\lib\index.js:136:9)
[2022-03-07 03:22:27][MJSONWP (641053f0)]     at AsyncLock.acquire (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\async-lock\lib\index.js:152:3)
[2022-03-07 03:22:27][MJSONWP (641053f0)]     at AndroidUiautomator2Driver.executeCommand (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:348:39)
[2022-03-07 03:22:27][MJSONWP (641053f0)]     at FlutterDriver.executeCommand (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-flutter-driver\lib\driver.ts:117:41)
[2022-03-07 03:22:27][MJSONWP (641053f0)]     at AppiumDriver.executeCommand (C:\Program Files\Appium\resources\app\node_modules\appium\lib\appium.js:563:36)
[2022-03-07 03:22:27][MJSONWP (641053f0)]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2022-03-07 03:22:27][MJSONWP (641053f0)]     at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:297:21)
[2022-03-07 03:22:27][HTTP] <-- POST /wd/hub/session/641053f0-4837-4327-b2e1-70e1179f7591/execute 501 4 ms - 113
[2022-03-07 03:22:27][HTTP] 
[2022-03-07 03:22:27][HTTP] --> GET /wd/hub/session/641053f0-4837-4327-b2e1-70e1179f7591/screenshot
[2022-03-07 03:22:27][HTTP] {}
[2022-03-07 03:22:27][MJSONWP (641053f0)] Calling AppiumDriver.getScreenshot() with args: ["641053f0-4837-4327-b2e1-70e1179f7591"]
[2022-03-07 03:22:27][FlutterDriver] Executing proxied driver command 'getScreenshot'
[2022-03-07 03:22:27][WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[2022-03-07 03:22:27][WD Proxy] Proxying [GET /screenshot] to [GET http://127.0.0.1:8212/wd/hub/session/77829b2b-9e29-4010-a1e5-00d005fda348/screenshot] with no body
[2022-03-07 03:22:29][WD Proxy] Got response with status 200: {"sessionId":"77829b2b-9e29-4010-a1e5-00d005fda348","value":"iVBORw0KGgoAAAANSUhEUgAABDgAAAkkCAYAAAD508+vAAAAAXNSR0IArs4c6QAAAARzQklUCAgI\nCHwIZIgAACAASURBVHic7F13oB1F1f/N3vfSew8BEiChhiLSQ5FqQkARQhcxNOlFEEkComhIAoiA\nIMECIsJHV+mg1AQphh6CEJoE0gmQhLT37s73x+7Mzs5O3d17341y9JH3dmfOnJmdcs5vzpwh3YZ0\npZCI0ugRIUR+ZSQxPePhw0fMY+OvS28qS5aJEAJKqZes7D0BRSjl1aUV2zMQ+IeU8r9VvFKyBIm8\nqvrI+UzvipCuzeW6ir+zfyuVCv/bpd3KoDAMMzLKZankEdPyuoEidCiTUIDlVo0JXlZAAMe6koCA\nhup2M31vJS/P9pV5q8YRkxEAaEiV6fKSXH5QCVLl6Mn+tSLWjt/AqQ4uZfrNW2VR5rsFQt+U2lL+\nlrbnOmLpw2q6XeTyQyT8AqktQvn7E5J5JuYjAMKqep4U+6qqDqJMKtlUZarmPpXcUXoAyMqTnTcJ\nCAm05fK0TjMSQJDmpZ4zKKihrozCaswjSK9nmfUpp2xqoghpwq8e4wUAAlJBNQyFv6O+x/oOa4No\nHgxAaYhqGPL3lXiuEvuC3GfYO95/pT7h0v/lMSPmk3UOVR6CaC7UjWtWT9NYYERpekZVySu2n/g3\ne6abd+T86XLz6a0mEvtzUAlS+hqb08osz3d+FfOJ+oFpDrHp0T46tK58J5kd2s2FHyEElUoFIQ1T\nMohzfUAChDTMrEMiD7Htfeqhaz8X3ZL/HVKmjCR1Ciq8XUMaglIa/a1o64ytQQGq0H3lPJm20nwT\nlZ0k5teNPRW/MNTP46nxFgSpZ0XsPRWp8jqXFarHASPVfKyjaug/j6jm9OQbJGPeZmfp2l/sL65j\nUNffxTQquVTP2beXn/uOyybn...
[2022-03-07 03:22:29][MJSONWP (641053f0)] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABDgAAAkkCAYAAAD508+vAAAAAXNSR0IArs4c6QAAAARzQklUCAgI\nCHwIZIgAACAASURBVHic7F13oB1F1f/N3vfSew8BEiChhiLSQ5FqQkARQhcxNOlFEEkComhIAoiA\nIMECIsJHV+mg1AQphh6CEJoE0gmQhLT37s73x+7Mzs5O3d17341y9JH3dmfOnJmdcs5vzpwh3YZ0\npZCI0ugRIUR+ZSQxPePhw0fMY+OvS28qS5aJEAJKqZes7D0BRSjl1aUV2zMQ+IeU8r9VvFKyBIm8\nqvrI+UzvipCuzeW6ir+zfyuVCv/bpd3KoDAMMzLKZankEdPyuoEidCiTUIDlVo0JXlZAAMe6koCA\nhup2M31vJS/P9pV5q8YRkxEAaEiV6fKSXH5QCVLl6Mn+tSLWjt/AqQ4uZfrNW2VR5rsFQt+U2lL+\nlrbnOmLpw2q6XeTyQyT8AqktQvn7E5J5JuYjAMKqep4U+6qqDqJMKtlUZarmPpXcUXoAyMqTnTcJ\nCAm05fK0TjMSQJDmpZ4zKKihrozCaswjSK9nmfUpp2xqoghpwq8e4wUAAlJBNQyFv6O+x/oOa4No\nHgxAaYhqGPL3lXiuEvuC3GfYO95/pT7h0v/lMSPmk3UOVR6CaC7UjWtWT9NYYERpekZVySu2n/g3\ne6abd+T86XLz6a0mEvtzUAlS+hqb08osz3d+FfOJ+oFpDrHp0T46tK58J5kd2s2FHyEElUoFIQ1T\nMohzfUAChDTMrEMiD7Htfeqhaz8X3ZL/HVKmjCR1Ciq8XUMaglIa/a1o64ytQQGq0H3lPJm20nwT\nlZ0k5teNPRW/MNTP46nxFgSpZ0XsPRWp8jqXFarHASPVfKyjaug/j6jm9OQbJGPeZmfp2l/sL65j\nUNffxTQquVTP2beXn/uOyybn1A1AeRcwXaPk4UegVjoy6TQ85Xxi5zQahBRc+fT5yPUkH7CnXqSb\nuPMsYB...
[2022-03-07 03:22:29][HTTP] <-- GET /wd/hub/session/641053f0-4837-4327-b2e1-70e1179f7591/screenshot 200 1220 ms - 1124600
[2022-03-07 03:22:29][HTTP] 
[2022-03-07 03:22:29][HTTP] --> DELETE /wd/hub/session/641053f0-4837-4327-b2e1-70e1179f7591
[2022-03-07 03:22:29][HTTP] {}
[2022-03-07 03:22:29][MJSONWP (641053f0)] Calling AppiumDriver.deleteSession() with args: ["641053f0-4837-4327-b2e1-70e1179f7591"]
[2022-03-07 03:22:29][BaseDriver] Event 'quitSessionRequested' logged at 1646637749192 (15:22:29 GMT+0800 (中国标准时间))
[2022-03-07 03:22:29][Appium] Removing session 641053f0-4837-4327-b2e1-70e1179f7591 from our master session list
[2022-03-07 03:22:29][FlutterDriver] Deleting Flutter Driver session
[2022-03-07 03:22:29][UiAutomator2] Deleting UiAutomator2 session
[2022-03-07 03:22:29][UiAutomator2] Deleting UiAutomator2 server session
[2022-03-07 03:22:29][WD Proxy] Matched '/' to command name 'deleteSession'
[2022-03-07 03:22:29][WD Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:8212/wd/hub/session/77829b2b-9e29-4010-a1e5-00d005fda348] with no body
[2022-03-07 03:22:29][WD Proxy] Got response with status 200: {"sessionId":"77829b2b-9e29-4010-a1e5-00d005fda348","value":null}
[2022-03-07 03:22:29][UiAutomator2] Resetting IME to 'io.appium.settings/.UnicodeIME'
[2022-03-07 03:22:29][ADB] Running 'C:\Users\aaa\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s d8391da30721 shell ime set io.appium.settings/.UnicodeIME'
[2022-03-07 03:22:29][ADB] Running 'C:\Users\aaa\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s d8391da30721 shell am force-stop '
[2022-03-07 03:22:29][Logcat] Stopping logcat capture
[2022-03-07 03:22:29][ADB] Removing forwarded port socket connection: 8212 
[2022-03-07 03:22:29][ADB] Running 'C:\Users\aaa\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s d8391da30721 forward --remove tcp:8212'
[2022-03-07 03:22:29][UiAutomator2] Restoring hidden api policy to the device default configuration
[2022-03-07 03:22:29][ADB] Running 'C:\Users\aaa\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s d8391da30721 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[2022-03-07 03:22:29][Instrumentation] .
[2022-03-07 03:22:29][Instrumentation] Time: 90.109
[2022-03-07 03:22:29][Instrumentation] 
[2022-03-07 03:22:29][Instrumentation] OK (1 test)
[2022-03-07 03:22:29][BaseDriver] Event 'quitSessionFinished' logged at 1646637749695 (15:22:29 GMT+0800 (中国标准时间))
[2022-03-07 03:22:29][MJSONWP (641053f0)] Received response: null
[2022-03-07 03:22:29][MJSONWP (641053f0)] But deleting session, so not returning
[2022-03-07 03:22:29][MJSONWP (641053f0)] Responding to client with driver.deleteSession() result: null
[2022-03-07 03:22:29][HTTP] <-- DELETE /wd/hub/session/641053f0-4837-4327-b2e1-70e1179f7591 200 504 ms - 76
[2022-03-07 03:22:29][HTTP] 
[2022-03-07 03:22:29][Instrumentation] The process has exited with code 0

**Comment by KazuCocoa** [comment]
perhaps something driver was old one...?
