### ISSUE TITLE
Impossible to launch the iOS app on real device with automationName: "Flutter"

### ISSUE THREAD

**Issue by agpdl** [appium-userland/appium-flutter-driver#277]
When setting the capabilities to use the automationName: "Flutter" the driver is unable to create a new session.
Replacing the automationName with XCUITest works to launch the app on iOS but I'm unable to locate flutter elements.

On the other side, for Android, it works perfectly using Flutter as **automationName**.

Capabilities used:
```
    platformName: 'iOS',
    platformVersion: '14.4',
    deviceName: 'Bill Gates',
    udid: '**************************',
    noReset: false,
    bundleId: 'com.corteva.flight.dev.agust',
    automationName: 'Flutter'
```

Result logs:
```
2022-05-11T18:28:08.904Z ERROR webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
2022-05-11T18:28:08.904Z ERROR webdriver: unknown error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getErrorFromResponseBody (/Users/agustinponcedeleon/Downloads/appium-flutter-driver-main/example/nodejs/node_modules/webdriver/build/utils.js:197:12)
    at NodeJSRequest._request (/Users/agustinponcedeleon/Downloads/appium-flutter-driver-main/example/nodejs/node_modules/webdriver/build/request/index.js:158:60)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async startWebDriverSession (/Users/agustinponcedeleon/Downloads/appium-flutter-driver-main/example/nodejs/node_modules/webdriver/build/utils.js:67:20)
    at async Function.newSession (/Users/agustinponcedeleon/Downloads/appium-flutter-driver-main/example/nodejs/node_modules/webdriver/build/index.js:46:45)
    at async Object.remote (/Users/agustinponcedeleon/Downloads/appium-flutter-driver-main/example/nodejs/node_modules/webdriverio/build/index.js:77:22)
    at async /Users/agustinponcedeleon/Downloads/appium-flutter-driver-main/example/nodejs/src/index.js:44:18
/Users/agustinponcedeleon/Downloads/appium-flutter-driver-main/example/nodejs/node_modules/webdriver/build/utils.js:72
        throw new Error('Failed to create session.\n' + message);
              ^

Error: Failed to create session.
An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at startWebDriverSession (/Users/agustinponcedeleon/Downloads/appium-flutter-driver-main/example/nodejs/node_modules/webdriver/build/utils.js:72:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.newSession (/Users/agustinponcedeleon/Downloads/appium-flutter-driver-main/example/nodejs/node_modules/webdriver/build/index.js:46:45)
    at async Object.remote (/Users/agustinponcedeleon/Downloads/appium-flutter-driver-main/example/nodejs/node_modules/webdriverio/build/index.js:77:22)
    at async /Users/agustinponcedeleon/Downloads/appium-flutter-driver-main/example/nodejs/src/index.js:44:18
```

**Comment by KazuCocoa** [comment]
`Cannot read property 'match' of undefined` usually means this driver cannot find the Dart VM websocket connection.
For example, the iOS app was not debug/profile built.
