### ISSUE TITLE
Could not get unknown property 'ndkVersion' for object of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension.

### ISSUE THREAD

**Issue by sahil-innostax** [appium-userland/appium-flutter-driver#295]
Error while running android app

Could not get unknown property 'ndkVersion' for object of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension.

**Comment by KazuCocoa** [comment]
Could you share the full appium log?

**Comment by sahil-innostax** [comment]
> Could you share the full appium log?

> appium@1.0.0 android /Users/sahilkhurana/final-flutter/appium
> APPIUM_OS=android npm start


> appium@1.0.0 start /Users/sahilkhurana/final-flutter/appium
> node test.js

Initial app testing
2022-07-01T07:09:18.248Z INFO webdriverio: Initiate new session using the webdriver protocol
sessionRequest
/session endpoint
sessionRequestend
2022-07-01T07:09:18.251Z INFO webdriver: [POST] http://localhost:4723/wd/hub/session
2022-07-01T07:09:18.251Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      platformName: 'Android',
      deviceName: 'emulator-5554',
      platformVersion: '13',
      app: '/Users/sahilkhurana/final-flutter/build/app/outputs/apk/debug/app-debug.apk',
      automationName: 'Flutter'
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    platformName: 'Android',
    deviceName: 'emulator-5554',
    platformVersion: '13',
    app: '/Users/sahilkhurana/final-flutter/build/app/outputs/apk/debug/app-debug.apk',
    automationName: 'Flutter'
  }
}
{
  value: {
    error: 'unknown error',
    message: "An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined",
    stacktrace: "UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined\n" +
      '    at getResponseForW3CError (/Users/sahilkhurana/.nvm/versions/node/v12.22.8/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)\n' +
      '    at asyncHandler (/Users/sahilkhurana/.nvm/versions/node/v12.22.8/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)'
  }
} here caps
2022-07-01T07:09:35.457Z WARN webdriver: Request failed due to An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
2022-07-01T07:09:35.459Z INFO webdriver: Retrying 1/3
2022-07-01T07:09:35.460Z INFO webdriver: [POST] http://localhost:4723/wd/hub/session
2022-07-01T07:09:35.460Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      platformName: 'Android',
      deviceName: 'emulator-5554',
      platformVersion: '13',
      app: '/Users/sahilkhurana/final-flutter/build/app/outputs/apk/debug/app-debug.apk',
      automationName: 'Flutter'
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    platformName: 'Android',
    deviceName: 'emulator-5554',
    platformVersion: '13',
    app: '/Users/sahilkhurana/final-flutter/build/app/outputs/apk/debug/app-debug.apk',
    automationName: 'Flutter'
  }
}
{
  value: {
    error: 'unknown error',
    message: "An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined",
    stacktrace: "UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined\n" +
      '    at getResponseForW3CError (/Users/sahilkhurana/.nvm/versions/node/v12.22.8/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)\n' +
      '    at asyncHandler (/Users/sahilkhurana/.nvm/versions/node/v12.22.8/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)'
  }
} here caps
2022-07-01T07:09:42.254Z WARN webdriver: Request failed due to An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
2022-07-01T07:09:42.254Z INFO webdriver: Retrying 2/3
2022-07-01T07:09:42.254Z INFO webdriver: [POST] http://localhost:4723/wd/hub/session
2022-07-01T07:09:42.254Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      platformName: 'Android',
      deviceName: 'emulator-5554',
      platformVersion: '13',
      app: '/Users/sahilkhurana/final-flutter/build/app/outputs/apk/debug/app-debug.apk',
      automationName: 'Flutter'
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    platformName: 'Android',
    deviceName: 'emulator-5554',
    platformVersion: '13',
    app: '/Users/sahilkhurana/final-flutter/build/app/outputs/apk/debug/app-debug.apk',
    automationName: 'Flutter'
  }
}
{
  value: {
    error: 'unknown error',
    message: "An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined",
    stacktrace: "UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined\n" +
      '    at getResponseForW3CError (/Users/sahilkhurana/.nvm/versions/node/v12.22.8/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)\n' +
      '    at asyncHandler (/Users/sahilkhurana/.nvm/versions/node/v12.22.8/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)'
  }
} here caps
2022-07-01T07:09:48.272Z WARN webdriver: Request failed due to An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
2022-07-01T07:09:48.273Z INFO webdriver: Retrying 3/3
2022-07-01T07:09:48.273Z INFO webdriver: [POST] http://localhost:4723/wd/hub/session
2022-07-01T07:09:48.274Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      platformName: 'Android',
      deviceName: 'emulator-5554',
      platformVersion: '13',
      app: '/Users/sahilkhurana/final-flutter/build/app/outputs/apk/debug/app-debug.apk',
      automationName: 'Flutter'
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    platformName: 'Android',
    deviceName: 'emulator-5554',
    platformVersion: '13',
    app: '/Users/sahilkhurana/final-flutter/build/app/outputs/apk/debug/app-debug.apk',
    automationName: 'Flutter'
  }
}
{
  value: {
    error: 'unknown error',
    message: "An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined",
    stacktrace: "UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined\n" +
      '    at getResponseForW3CError (/Users/sahilkhurana/.nvm/versions/node/v12.22.8/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)\n' +
      '    at asyncHandler (/Users/sahilkhurana/.nvm/versions/node/v12.22.8/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)'
  }
} here caps
2022-07-01T07:09:54.398Z ERROR webdriver: Request failed due to unknown error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getErrorFromResponseBody (/Users/sahilkhurana/final-flutter/appium/node_modules/webdriver/build/utils.js:185:10)
    at Request._callback (/Users/sahilkhurana/final-flutter/appium/node_modules/webdriver/build/request.js:116:64)
    at Request.self.callback (/Users/sahilkhurana/final-flutter/appium/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.<anonymous> (/Users/sahilkhurana/final-flutter/appium/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at IncomingMessage.<anonymous> (/Users/sahilkhurana/final-flutter/appium/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:420:28)
(node:44093) UnhandledPromiseRejectionWarning: unknown error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getErrorFromResponseBody (/Users/sahilkhurana/final-flutter/appium/node_modules/webdriver/build/utils.js:185:10)
    at Request._callback (/Users/sahilkhurana/final-flutter/appium/node_modules/webdriver/build/request.js:116:64)
    at Request.self.callback (/Users/sahilkhurana/final-flutter/appium/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.<anonymous> (/Users/sahilkhurana/final-flutter/appium/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at IncomingMessage.<anonymous> (/Users/sahilkhurana/final-flutter/appium/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:420:28)
(node:44093) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:44093) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
MacBook-Air-2:appium sahilkhurana$ 
MacBook-Air-2:appium sahilkhurana$ 
MacBook-Air-2:appium sahilkhurana$ 
MacBook-Air-2:appium sahilkhurana$ npm run android

> appium@1.0.0 android /Users/sahilkhurana/final-flutter/appium
> APPIUM_OS=android npm start


> appium@1.0.0 start /Users/sahilkhurana/final-flutter/appium
> node test.js

Initial app testing
2022-07-01T07:12:29.914Z INFO webdriverio: Initiate new session using the webdriver protocol
sessionRequest
/session endpoint
sessionRequestend
2022-07-01T07:12:29.916Z INFO webdriver: [POST] http://localhost:4723/wd/hub/session
2022-07-01T07:12:29.917Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      platformName: 'Android',
      deviceName: 'emulator-5554',
      platformVersion: '13',
      app: '/Users/sahilkhurana/final-flutter/build/app/outputs/apk/debug/app-debug.apk',
      automationName: 'Flutter'
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    platformName: 'Android',
    deviceName: 'emulator-5554',
    platformVersion: '13',
    app: '/Users/sahilkhurana/final-flutter/build/app/outputs/apk/debug/app-debug.apk',
    automationName: 'Flutter'
  }
}
{
  value: {
    error: 'unknown error',
    message: "An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined",
    stacktrace: "UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined\n" +
      '    at getResponseForW3CError (/Users/sahilkhurana/.nvm/versions/node/v12.22.8/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)\n' +
      '    at asyncHandler (/Users/sahilkhurana/.nvm/versions/node/v12.22.8/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)'
  }
} here caps
2022-07-01T07:12:42.109Z WARN webdriver: Request failed due to An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
2022-07-01T07:12:42.113Z INFO webdriver: Retrying 1/3
2022-07-01T07:12:42.113Z INFO webdriver: [POST] http://localhost:4723/wd/hub/session
2022-07-01T07:12:42.113Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      platformName: 'Android',
      deviceName: 'emulator-5554',
      platformVersion: '13',
      app: '/Users/sahilkhurana/final-flutter/build/app/outputs/apk/debug/app-debug.apk',
      automationName: 'Flutter'
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    platformName: 'Android',
    deviceName: 'emulator-5554',
    platformVersion: '13',
    app: '/Users/sahilkhurana/final-flutter/build/app/outputs/apk/debug/app-debug.apk',
    automationName: 'Flutter'
  }
}
{
  value: {
    error: 'unknown error',
    message: "An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined",
    stacktrace: "UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined\n" +
      '    at getResponseForW3CError (/Users/sahilkhurana/.nvm/versions/node/v12.22.8/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)\n' +
      '    at asyncHandler (/Users/sahilkhurana/.nvm/versions/node/v12.22.8/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)'
  }
} here caps
2022-07-01T07:12:48.047Z WARN webdriver: Request failed due to An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
2022-07-01T07:12:48.048Z INFO webdriver: Retrying 2/3
2022-07-01T07:12:48.049Z INFO webdriver: [POST] http://localhost:4723/wd/hub/session
2022-07-01T07:12:48.049Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      platformName: 'Android',
      deviceName: 'emulator-5554',
      platformVersion: '13',
      app: '/Users/sahilkhurana/final-flutter/build/app/outputs/apk/debug/app-debug.apk',
      automationName: 'Flutter'
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    platformName: 'Android',
    deviceName: 'emulator-5554',
    platformVersion: '13',
    app: '/Users/sahilkhurana/final-flutter/build/app/outputs/apk/debug/app-debug.apk',
    automationName: 'Flutter'
  }
}
{
  value: {
    error: 'unknown error',
    message: "An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined",
    stacktrace: "UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined\n" +
      '    at getResponseForW3CError (/Users/sahilkhurana/.nvm/versions/node/v12.22.8/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)\n' +
      '    at asyncHandler (/Users/sahilkhurana/.nvm/versions/node/v12.22.8/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)'
  }
} here caps
2022-07-01T07:12:53.697Z WARN webdriver: Request failed due to An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
2022-07-01T07:12:53.697Z INFO webdriver: Retrying 3/3
2022-07-01T07:12:53.698Z INFO webdriver: [POST] http://localhost:4723/wd/hub/session
2022-07-01T07:12:53.698Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      platformName: 'Android',
      deviceName: 'emulator-5554',
      platformVersion: '13',
      app: '/Users/sahilkhurana/final-flutter/build/app/outputs/apk/debug/app-debug.apk',
      automationName: 'Flutter'
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    platformName: 'Android',
    deviceName: 'emulator-5554',
    platformVersion: '13',
    app: '/Users/sahilkhurana/final-flutter/build/app/outputs/apk/debug/app-debug.apk',
    automationName: 'Flutter'
  }
}
{
  value: {
    error: 'unknown error',
    message: "An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined",
    stacktrace: "UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined\n" +
      '    at getResponseForW3CError (/Users/sahilkhurana/.nvm/versions/node/v12.22.8/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)\n' +
      '    at asyncHandler (/Users/sahilkhurana/.nvm/versions/node/v12.22.8/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)'
  }
} here caps
2022-07-01T07:12:59.253Z ERROR webdriver: Request failed due to unknown error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getErrorFromResponseBody (/Users/sahilkhurana/final-flutter/appium/node_modules/webdriver/build/utils.js:185:10)
    at Request._callback (/Users/sahilkhurana/final-flutter/appium/node_modules/webdriver/build/request.js:116:64)
    at Request.self.callback (/Users/sahilkhurana/final-flutter/appium/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.<anonymous> (/Users/sahilkhurana/final-flutter/appium/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at IncomingMessage.<anonymous> (/Users/sahilkhurana/final-flutter/appium/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:420:28)
(node:46371) UnhandledPromiseRejectionWarning: unknown error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getErrorFromResponseBody (/Users/sahilkhurana/final-flutter/appium/node_modules/webdriver/build/utils.js:185:10)
    at Request._callback (/Users/sahilkhurana/final-flutter/appium/node_modules/webdriver/build/request.js:116:64)
    at Request.self.callback (/Users/sahilkhurana/final-flutter/appium/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.<anonymous> (/Users/sahilkhurana/final-flutter/appium/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at IncomingMessage.<anonymous> (/Users/sahilkhurana/final-flutter/appium/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:420:28)
(node:46371) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:46371) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by KazuCocoa** [comment]
It was client one. What about the server side one?

> 2022-07-01T07:12:59.253Z ERROR webdriver: Request failed due to unknown error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined

At least this is an issue. Could you try out latest appium-flutter-driver? It is 1.2.0 with Appium 2.

**Comment by KazuCocoa** [comment]
Close for now. Feel free to comment here if the issue was not `match` message stuff. Afaik, the latest driver version 1.2.0 has some improvements for it.

**Comment by sahil-innostax** [comment]
> Close for now. Feel free to comment here if the issue was not `match` message stuff. Afaik, the latest driver version 1.2.0 has some improvements for it.

Thanks @KazuCocoa 
It worked as per your suggestion
