### ISSUE TITLE
Having issue with flutter 3.0.0 debug apk, current script working on flutter 2.10.5 debug apk. Does appium driver support automation for flutter 3?

### ISSUE THREAD

**Issue by zyk77** [appium-userland/appium-flutter-driver#296]
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'TFS-PC-ZY', ip: '169.254.211.216', os.name: 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_181'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getResponseForW3CError (C:\Users\ZYTAN\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ZYTAN\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'TFS-PC-ZY', ip: '169.254.211.216', os.name: 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_181'
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:216)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:225)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:363)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:89)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:99)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:97)
	at com.test.rt.App.appium(App.java:69)
	at com.test.rt.App.main(App.java:29)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:193)
	... 15 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'TFS-PC-ZY', ip: '169.254.211.216', os.name: 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_181'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getResponseForW3CError (C:\Users\ZYTAN\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ZYTAN\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	... 20 more

**Comment by zyk77** [comment]
This is my appium setting. i am using java version library. https://github.com/appium-userland/appium-flutter-driver/releases/tag/kotlin-finder-0.0.4. Can anyone guide me on this issue?

		DesiredCapabilities caps = new DesiredCapabilities();
		caps.setCapability("deviceName", "My Phone");
		caps.setCapability("udid", "CMR6R18808000340"); //Give Device ID  
		caps.setCapability("platformVersion", "9");
		caps.setCapability("platformName", "Android");
		//		caps.setCapability("app", "D:workspacePhoneGap/rt/app-debug_2.10.5_enable.apk");
		caps.setCapability("app", "D:workspacePhoneGap/rt/app-debug_3.0.3_enable.apk");		
		caps.setCapability("appPackage", "com.example.hello_world");
		caps.setCapability("appActivity", "com.example.hello_world.MainActivity");
		caps.setCapability("automationName", "Flutter");

		try {
			URL url = new URL("http://0.0.0.0:4723/wd/hub");

			driver = new AndroidDriver(url, caps);
			FlutterFinder find = new FlutterFinder(driver); 

			MobileElement element = find.byValueKey("abc");
			element.click();

		} catch (MalformedURLException e) {

			System.out.println(e.getMessage());

		}

**Comment by KazuCocoa** [comment]
Feel free to comment here if the issue still exists with the 1.2.0.

**Comment by zyk77** [comment]
D:\rt2\src\main\rt\pro\truongsinh\appium_flutter\finder\ancestor.kt:12:27
Kotlin: Type mismatch: inferred type is Any but {Comparable<{Boolean & String}> & java.io.Serializable} was expected

i am having this error when using appium-flutter-driver 1.2.0 and 1.4.0. What seem to be for problem?

**Comment by KazuCocoa** [comment]
I guess it could be fixed by https://github.com/appium-userland/appium-flutter-driver/pull/308

**Comment by zyk77** [comment]
m["of"] = of.getRawMap() as String
  m["matching"] = matching.getRawMap() as String

When using kotlin source, i need to defined the type of the variable like above in ( ancestor.kt & descendant.kt ) only i able to run the code. I am using kotlin 1.6.0. After running it work for apk 2.10.5, but still having error with flutter 3 apk. Tested using 1.4.0 and snapshot version.

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Failed to connect 30 times. Aborting.

**Comment by KazuCocoa** [comment]
> Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Failed to connect 30 times. Aborting.

What kind of observatory message did the logcat (android)/system log (ios) have?

Currently appium flutter driver expects:
https://github.com/appium-userland/appium-flutter-driver/blob/beaa1b9e3f692715db5d7e32d2c8839eb7399531/driver/lib/sessions/observatory.ts#L185-L191

**Comment by KazuCocoa** [comment]
The attached error was another one. Maybe your local apk was not the correct path.

> Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: The application at 'D:workspacePhoneGap/rt/app-debug_JL.apk' does not exist or is not accessible


My previous comment one is the result of adb logcat. it is not client-side error log, unfortunately.

**Comment by zyk77** [comment]
Sorry about that, i run the wrong repo just now. I think i found the issue. My pc is blocking the socket connection for some reason. An popup appear after a few tried requesting to allow permission for socket connection. Now it seem to be working. I will try again tomorrow to make sure it working. Thank You.
