### ISSUE TITLE
pullFile "method has not yet been implemented" in Appium2 flutter driver

### ISSUE THREAD

**Issue by zyk77** [appium-userland/appium-flutter-driver#318]
i am trying to extract file from the device using pullFile.
     
		DesiredCapabilities caps = new DesiredCapabilities();
		caps.setCapability("deviceName", "My Phone");
		caps.setCapability("udid", "CMR6R18808000340"); 
		caps.setCapability("platformVersion", "9");
		caps.setCapability("platformName", "Android");
		caps.setCapability("appPackage", "com.example.hello_world");
		caps.setCapability("appActivity", "com.example.hello_world.MainActivity");
                caps.setCapability("app", "D:workspacePhoneGap/rt/app-debug_attachPdf.apk");
		caps.setCapability("automationName", "Flutter");

               URL url = new URL("http://0.0.0.0:4723/");
               driver = new AndroidDriver(url, caps);
               byte[] fileBase64 = driver.pullFile("/sdcard/Download/sample2.pdf");

I got the error "method not been implement" when i try to run driver.pullFile using Appium 2 Flutter Driver. When i set the automationName to UiAutomator2 the function seem to be working. What seem to be the problem?

```
org.openqa.selenium.UnsupportedCommandException: {"value":{"error":"unknown method","message":"Method has not yet been implemented","stacktrace":"NotYetImplementedError: Method has not yet been implemented\n    at FlutterDriver.executeCommand (C:\\Users\\ZYTAN\\.appium\\node_modules\\appium-flutter-driver\\node_modules\\@appium\\base-driver\\lib\\basedriver\\driver.js:67:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at FlutterDriver.executeCommand (C:\\Users\\ZYTAN\\.appium\\node_modules\\appium-flutter-driver\\lib\\driver.ts:139:16)\n    at defaultBehavior (C:\\Users\\ZYTAN\\AppData\\Roaming\\nvm\\v16.15.1\\node_modules\\appium\\lib\\appium.js:670:14)\n    at AppiumDriver.executeWrappedCommand (C:\\Users\\ZYTAN\\AppData\\Roaming\\nvm\\v16.15.1\\node_modules\\appium\\lib\\appium.js:760:16)\n    at AppiumDriver.executeCommand (C:\\Users\\ZYTAN\\AppData\\Roaming\\nvm\\v16.15.1\\node_modules\\appium\\lib\\appium.js:682:17)\n    at asyncHandler (C:\\Users\\ZYTAN\\AppData\\Roaming\\nvm\\v16.15.1\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\protocol.js:339:19)"}}
Command duration or timeout: 79 milliseconds
Build info: version: '4.3.0', revision: 'a4995e2c09*'
System info: host: 'TFS-PC-ZY', ip: '169.254.211.216', os.name: 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_181'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [437f2884-2074-4db8-90f0-a9e50daae641, pullFile {path=/sdcard/Download/sample2.pdf}]
Capabilities {appium:address: 0.0.0.0, appium:allowCors: false, appium:allowInsecure: [], appium:app: D:workspacePhoneGap/rt/app-..., appium:appActivity: com.example.hello_world.Mai..., appium:appPackage: com.example.hello_world, appium:automationName: Flutter, appium:basePath: , appium:callbackPort: 4723, appium:debugLogSpacing: false, appium:denyInsecure: [], appium:deviceName: My Phone, appium:driver: {xcuitest: {wdaLocalPort: 8100}}, appium:fastReset: true, appium:keepAliveTimeout: 600, appium:localTimezone: false, appium:logNoColors: false, appium:logTimestamp: false, appium:loglevel: debug, appium:longStacktrace: false, appium:noPermsCheck: false, appium:platformVersion: 9, appium:port: 4723, appium:relaxedSecurityEnabled: false, appium:sessionOverride: false, appium:skipUninstall: true, appium:strictCaps: false, appium:subcommand: server, appium:tmpDir: C:\Users\ZYTAN\AppData\Loca..., appium:udid: CMR6R18808000340, appium:useDrivers: [], appium:usePlugins: [], platformName: ANDROID}
Session ID: 437f2884-2074-4db8-90f0-a9e50daae641
end
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:217)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:169)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:624)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:262)
	at io.appium.java_client.PullsFiles.pullFile(PullsFiles.java:44)
	at com.test.rt.App.appium(App.java:107)
	at com.test.rt.App.main(App.java:34)

```

**Comment by KazuCocoa** [comment]
Did you change the context to NATIVE_APP? https://github.com/appium-userland/appium-flutter-driver#note

FLUTTER context supports only https://github.com/appium-userland/appium-flutter-driver#commands

**Comment by KazuCocoa** [comment]
Please try out the command in the NATIVE_APP context.
