### ISSUE TITLE
Flutter Driver scroll Until Error

### ISSUE THREAD

**Issue by ArunGanesh88** [appium-userland/appium-flutter-driver#329]
When using appium flutter driver with web driver io and scroll until element is visible we are getting the below error.

` unknown error: An unknown server-side error occurred while processing the command. Original error: Cannot execute command scroll, server reponse {
         "isError": true,
         "response": "Uncaught extension error while executing scroll: IntegerDivisionByZeroException\n#0      Duration.~/ (dart:core/duration.dart:219:24)\n#1      CommandHandlerFactory._scroll (package:flutter_driver/src/common/handler_factory.dart:369:51)\n<asynchronous suspension>\n#2      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:372:31)\n<asynchronous suspension>\n#3      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:851:18)\n<asynchronous suspension>\n",
         "type": "_extensionType",
         "method": "ext.flutter.driver"
       }`

**Comment by ArunGanesh88** [comment]
This is the code where it is failing
`await this.driver.execute('flutter:scrollUntilVisible',byType('ListView'), {item:byText('objectText'), dyScroll: -400});`

**Comment by KazuCocoa** [comment]
Could you share the server log to see the version etc?

The error itself was from flutter_driver, so need to investigate the cause in flutter code

**Comment by densa** [comment]
@KazuCocoa I think it because of our last changes. https://github.com/appium-userland/appium-flutter-driver/commit/0b7260935344f55200ea18a9f47dec781818a76f#diff-f494fc757a40cb504b8bfc5328219b9f986260431da31a9b1bae0553752b71e6L173
I've installed version 1.6.0 and all works good
 

```
debug] [FlutterDriver@ff73 (33b580cb)] Calling AppiumDriver.execute() with args: ["flutter:scroll",["eyJmaW5kZXJUeXBlIjoiQnlUeXBlIiwidHlwZSI6Ikxpc3RWaWV3In0",{"dx":0,"dy":-500,"durationMilliseconds":200,"frequency":30}],"33b580cb-6034-404b-b706-9c973c315fb8"]
[debug] [FlutterDriver] Executing Flutter driver command 'execute'
[debug] [FlutterDriver] >>> {"command":"scroll","finderType":"ByType","type":"ListView","dx":0,"dy":-500,"duration":200000,"frequency":30}
[debug] [FlutterDriver] <<< {"isError":false,"response":{},"type":"_extensionType","method":"ext.flutter.driver"} | previous command scroll
[debug] [FlutterDriver@ff73 (33b580cb)] Responding to client with driver.execute() result: {}
[HTTP] <-- POST /wd/hub/session/33b580cb-6034-404b-b706-9c973c315fb8/execute/sync 200 266 ms - 12
```

but in version 1.7.0 scroll fail with 
```
[debug] [FlutterDriver@6a72 (bf6ad538)] Calling AppiumDriver.execute() with args: ["flutter:scroll",["eyJmaW5kZXJUeXBlIjoiQnlUeXBlIiwidHlwZSI6Ikxpc3RWaWV3In0",{"dx":0,"dy":-500,"durationMilliseconds":200,"frequency":30}],"bf6ad538-8563-49d8-824a-aabb45209756"]
[debug] [FlutterDriver] Executing Flutter driver command 'execute'
[debug] [FlutterDriver] >>> {"command":"scroll","finderType":"ByType","type":"ListView","dx":0,"dy":-500,"duration":200,"frequency":30}
[debug] [FlutterDriver] <<< {"isError":true,"response":"Uncaught extension error while executing scroll: IntegerDivisionByZeroException\n#0      Duration.~/ (dart:core/duration.dart:219:24)\n#1      CommandHandlerFactory._scroll (package:flutter_driver/src/common/handler_factory.dart:369:51)\n<asynchronous suspension>\n#2      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:372:31)\n<asynchronous suspension>\n#3      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:851:18)\n<asynchronous suspension>\n","type":"_extensionType","method":"ext.flutter.driver"} | previous command scroll
[debug] [FlutterDriver@6a72 (bf6ad538)] Encountered internal error running command: Error: Cannot execute command scroll, server reponse {
[debug] [FlutterDriver@6a72 (bf6ad538)]   "isError": true,
[debug] [FlutterDriver@6a72 (bf6ad538)]   "response": "Uncaught extension error while executing scroll: IntegerDivisionByZeroException\n#0      Duration.~/ (dart:core/duration.dart:219:24)\n#1      CommandHandlerFactory._scroll (package:flutter_driver/src/common/handler_factory.dart:369:51)\n<asynchronous suspension>\n#2      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:372:31)\n<asynchronous suspension>\n#3      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:851:18)\n<asynchronous suspension>\n",
[debug] [FlutterDriver@6a72 (bf6ad538)]   "type": "_extensionType",
[debug] [FlutterDriver@6a72 (bf6ad538)]   "method": "ext.flutter.driver"
[debug] [FlutterDriver@6a72 (bf6ad538)] }
[debug] [FlutterDriver@6a72 (bf6ad538)]     at FlutterDriver.executeElementCommand (/Users/d3n5a/.appium/node_modules/appium-flutter-driver/lib/sessions/observatory.ts:178:11)
[debug] [FlutterDriver@6a72 (bf6ad538)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [FlutterDriver@6a72 (bf6ad538)]     at scroll (/Users/d3n5a/.appium/node_modules/appium-flutter-driver/lib/commands/execute/scroll.ts:34:10)
[HTTP] <-- POST /wd/hub/session/bf6ad538-8563-49d8-824a-aabb45209756/execute/sync 500 3 ms - 1925
[HTTP]
```

**Comment by KazuCocoa** [comment]
I see. I read the flutter's code.

The scroll's duration was "microseconds", so it should not remove the `*1000`, but others should.
https://github.com/flutter/flutter/blob/master/packages/flutter_driver/lib/src/common/gesture.dart#L33-L38

**Comment by ArunGanesh88** [comment]
@KazuCocoa  I tried with 1.16.0 it is working as expected, Thanks.

**Comment by KazuCocoa** [comment]
v1.7.1 has the fix
