### ISSUE TITLE
Cannot find module 'appium/support'

### ISSUE THREAD

**Issue by FireLizard** [appium-userland/appium-flutter-driver#334]
When trying to install this error message occurs:

```
$ npm i -g appium-flutter-driver
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/appium-flutter-driver/node_modules/appium-chromedriver
npm ERR! command failed
npm ERR! command sh -c node install-npm.js
npm ERR! [14:56:28] Error installing Chromedriver: Cannot find module 'appium/support'
npm ERR! Require stack:
npm ERR! - /usr/local/lib/node_modules/appium-flutter-driver/node_modules/appium-chromedriver/build/lib/install.js
npm ERR! - /usr/local/lib/node_modules/appium-flutter-driver/node_modules/appium-chromedriver/install-npm.js
npm ERR! [14:56:28] Error: Cannot find module 'appium/support'
npm ERR! Require stack:
npm ERR! - /usr/local/lib/node_modules/appium-flutter-driver/node_modules/appium-chromedriver/build/lib/install.js
npm ERR! - /usr/local/lib/node_modules/appium-flutter-driver/node_modules/appium-chromedriver/install-npm.js
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:804:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1022:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:102:18)
npm ERR!     at Object.<anonymous> (/usr/local/lib/node_modules/appium-flutter-driver/node_modules/appium-chromedriver/lib/install.js:1:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1120:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:998:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1022:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:102:18)
npm ERR!     at main (/usr/local/lib/node_modules/appium-flutter-driver/node_modules/appium-chromedriver/install-npm.js:59:11)
npm ERR! [14:56:28] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable.
```

What can we do here?

**Comment by KazuCocoa** [comment]
appium-flutter-driver 1.0.0 and higher expect to work with appium 2. it expects to be installed as `appium driver install flutter` so it requires appium 2 is in the local first https://github.com/appium-userland/appium-flutter-driver#installation

**Comment by FireLizard** [comment]
Oh, I see. Thank you ;)
To install Appium 2 one should use `npm i -g appium@next` (https://appium.github.io/appium/docs/en/2.0/quickstart/install/)
