### ISSUE TITLE
Getting Error when running nested nested ancestor and descendant

### ISSUE THREAD

**Issue by ArunGanesh88** [appium-userland/appium-flutter-driver#337]
Hi,

When running the below code getting error, not sure if I am doing some mistake.

`driver.execute('flutter:waitFor',descendant({of: ancestor({of: byText('testUniqueName'),matching: byType('Container')}),matching: byText('2.00'),firstMatchOnly: true}) , 20000)`

Error:
 `      unknown error: An unknown server-side error occurred while processing the command. Original error: Cannot execute command waitFor, server reponse {
         "isError": true,
         "response": "Uncaught extension error while executing waitFor: type 'bool' is not a subtype of type 'String' in type cast\n#0      new LinkedHashMap.from.<anonymous closure> (dart:collection/linked_hash_map.dart:187:26)\n#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)\n#2      new LinkedHashMap.from (dart:collection/linked_hash_map.dart:186:11)\n#3      Descendant.deserialize (package:flutter_driver/src/common/find.dart:327:9)\n#4      DeserializeFinderFactory.deserializeFinder (package:flutter_driver/src/common/deserialization_factory.dart:32:44)\n#5      FlutterDriverExtension.deserializeFinder (package:flutter_driver/src/extension/extension.dart:401:18)\n#6      new CommandWithTarget.deserialize (package:flutter_driver/src/common/find.dart:32:30)\n#7      new WaitFor.deserialize (package:flutter_driver/src/common/find.dart:60:64)\n#8      DeserializeCommandFactory.deserializeCommand (package:flutter_driver/src/common/deserialization_factory.dart:57:38)\n#9      FlutterDriverExtension.deserializeCommand (package:flutter_driver/src/extension/extension.dart:421:18)\n#10     FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:365:31)\n#11     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:855:32)\n<asynchronous suspension>\n",
         "type": "_extensionType",
         "method": "ext.flutter.driver"
       }
           at getErrorFromResponseBody (/node_modules/webdriver/build/utils.js:198:12)
           at NodeJSRequest._request (/node_modules/webdriver/build/request/index.js:166:60)
           at processTicksAndRejections (node:internal/process/task_queues:96:5)
           at async Browser.wrapCommandFn (/node_modules/@wdio/utils/build/shim.js:137:29)
           at async Browser.wrapCommandFn (/node_modules/@wdio/utils/build/shim.js:137:29)`

**Comment by ArunGanesh88** [comment]
I am using Appium 2 with flutter driver 1.7.2

**Comment by KazuCocoa** [comment]
This should be fixed with the latest finders in this repository
