### ISSUE TITLE
appium-flutter-driver: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by nabilasiregar** [appium-userland/appium-flutter-driver#361]
### The problem
Use appium flutter driver to automate flutter app v3.0.5

### Environment
Appium 1.20.2
Node v11.10.0
npm v6.7.0
iPhone Simulator & Android Emulator
installed with 'npm i -g appium-flutter-driver'

### Other things to note
- I already have two machines working fine with one having the exact same environment as stated above and the other one with appium 1.21.0 & node v12.21.0 without having to upgrade to Appium 2. The issue im currently facing is when I want to setup appium flutter driver on a new machine/computer and this `Encountered internal error running command: TypeError: Cannot read property 'match' of undefined` error happened both in android and ios.
- The app already called enableFlutterDriverExtension
- For iOS, the app was built with 'flutter run' not 'flutter build' because with 'flutter build' the app will crash

### Appium debug info
```
[debug] [WebDriverAgent] WebDriverAgent information:
[debug] [WebDriverAgent] {
[debug] [WebDriverAgent]   "message": "WebDriverAgent is ready to accept commands",
[debug] [WebDriverAgent]   "state": "success",
[debug] [WebDriverAgent]   "os": {
[debug] [WebDriverAgent]     "testmanagerdVersion": 26,
[debug] [WebDriverAgent]     "name": "iOS",
[debug] [WebDriverAgent]     "sdkVersion": "15.4",
[debug] [WebDriverAgent]     "version": "12.4"
[debug] [WebDriverAgent]   },
[debug] [WebDriverAgent]   "ios": {
[debug] [WebDriverAgent]     "simulatorVersion": "12.4",
[debug] [WebDriverAgent]     "ip": "xxxxxx"
[debug] [WebDriverAgent]   },
[debug] [WebDriverAgent]   "ready": true,
[debug] [WebDriverAgent]   "build": {
[debug] [WebDriverAgent]     "upgradedAt": "1648182998744",
[debug] [WebDriverAgent]     "time": "Oct 28 2022 12:32:32",
[debug] [WebDriverAgent]     "productBundleIdentifier": "com.facebook.WebDriverAgentRunner"
[debug] [WebDriverAgent]   }
[debug] [WebDriverAgent] }
[debug] [WebDriverAgent] WebDriverAgent successfully started after 79807ms
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1666935221065 (12:33:41 GMT+0700 (Western Indonesia Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8104/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true,"defaultAlertAction":"accept"}],"alwaysMatch":{}}}
[debug] [WD Proxy] Got response with status 200: {"value":{"sessionId":"501751D8-CE80-4B6B-B6F8-886FE4E99174","capabilities":{"device":"iphone","browserName":"xxxxx","sdkVersion":"12.4","CFBundleIdentifier":"xxxxx"}},"sessionId":"501751D8-CE80-4B6B-B6F8-886FE4E99174"}
[WD Proxy] Determined the downstream protocol as 'W3C'
[debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1666935224254 (12:33:44 GMT+0700 (Western Indonesia Time))
[debug] [BaseDriver] Event 'wdaStarted' logged at 1666935224254 (12:33:44 GMT+0700 (Western Indonesia Time))
[XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[debug] [BaseDriver] Event 'orientationSet' logged at 1666935224254 (12:33:44 GMT+0700 (Western Indonesia Time))
[debug] [BaseDriver] The value of 'elementResponseAttributes' setting did not change. Skipping the update for it
[debug] [BaseDriver] The value of 'shouldUseCompactResponses' setting did not change. Skipping the update for it
[debug] [FlutterDriver] Deleting Flutter Driver session
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1666935224273 (12:33:44 GMT+0700 (Western Indonesia Time))
[debug] [W3C] Encountered internal error running command: TypeError: Cannot read property 'match' of undefined
[debug] [W3C]     at Object.exports.processLogToGetobservatory (/Users/macmini_test/.nvm/versions/node/v11.10.0/lib/node_modules/appium/node_modules/appium-flutter-driver/build/driver/lib/sessions/observatory.js:118:9)
[debug] [W3C]     at Object.exports.getObservatoryWsUri (/Users/macmini_test/.nvm/versions/node/v11.10.0/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/ios.ts:30:21)
[debug] [W3C]     at Object.exports.startIOSSession (/Users/macmini_test/.nvm/versions/node/v11.10.0/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/ios.ts:22:28)
[debug] [W3C]     at processTicksAndRejections (internal/process/next_tick.js:81:5)
[HTTP] <-- POST /wd/hub/session 500 92130 ms - 653
[HTTP] 
```

**Comment by KazuCocoa** [comment]
Please use the latest flutter driver for Flutter v3 with Appium 2

**Comment by KazuCocoa** [comment]
https://github.com/appium-userland/appium-flutter-driver/blob/main/driver/CHANGELOG.md#110
