### ISSUE TITLE
suddenly kills and cached session

### ISSUE THREAD

**Issue by Abhinav-Anand-Lambdatest** [appium-userland/appium-flutter-driver#365]
The session is not trying to create connection to dart observatory and  kills the cached connection  
```
[debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1668186662053 (17:11:02 GMT+0000 (Greenwich Mean Time))
[debug] [BaseDriver] Event 'wdaStarted' logged at 1668186662054 (17:11:02 GMT+0000 (Greenwich Mean Time))
[debug] [XCUITest] Setting initial orientation to 'PORTRAIT'
[debug] [WD Proxy] Matched '/orientation' to command name 'setOrientation'
[debug] [WD Proxy] Proxying [POST /orientation] to [POST http://127.0.0.1:11084/session/7BDFF815-C0F3-41B0-8787-5A1E02BD113F/orientation] with body: {"orientation":"PORTRAIT"}
[debug] [WD Proxy] Got response with status 200: {"value":null,"sessionId":"7BDFF815-C0F3-41B0-8787-5A1E02BD113F"}
[debug] [BaseDriver] Event 'orientationSet' logged at 1668186662098 (17:11:02 GMT+0000 (Greenwich Mean Time))
[debug] [BaseDriver] The value of 'elementResponseAttributes' setting did not change. Skipping the update for it
[debug] [BaseDriver] The value of 'shouldUseCompactResponses' setting did not change. Skipping the update for it
[debug] [WD Proxy] Matched '/session/f2984434-d059-4efe-82cb-769270f66175' to command name 'deleteSession'
[debug] [WD Proxy] Proxying [DELETE /session/f2984434-d059-4efe-82cb-769270f66175] to [DELETE http://127.0.0.1:11084/session/7BDFF815-C0F3-41B0-8787-5A1E02BD113F] with no body
[debug] [WD Proxy] Got response with status 200: {"value":null,"sessionId":null}
[DevCon Factory] Releasing connections for 00008110-000C0D0611BA801E device on any port number
[DevCon Factory] Found cached connections to release: ["00008110-000C0D0611BA801E:11084"]
[DevCon Factory] Releasing the listener for '00008110-000C0D0611BA801E:11084'
[debug] [iProxy@00008110:11084] Closing the connection
[debug] [DevCon Factory] Cached connections count: 0
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [FlutterDriver] Deleting Flutter Driver session
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1668186663227 (17:11:03 GMT+0000 (Greenwich Mean Time))
[debug] [W3C] Encountered internal error running command: TypeError: Cannot read properties of undefined (reading 'match')
[debug] [W3C]     at Object.exports.processLogToGetobservatory (/Users/ltadmin/Documents/appium/latest/node_modules/appium/node_modules/appium-flutter-driver/build/driver/lib/sessions/observatory.js:118:9)
[debug] [W3C]     at Object.exports.getObservatoryWsUri (/Users/ltadmin/Documents/appium/latest/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/ios.ts:77:21)
[debug] [W3C]     at Object.exports.startIOSSession (/Users/ltadmin/Documents/appium/latest/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/ios.ts:31:30)
[debug] [W3C]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [W3C]     at FlutterDriver.exports.createSession (/Users/ltadmin/Documents/appium/latest/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/session.ts:15:47)
[debug] [W3C]     at AppiumDriver.createSession (/Users/ltadmin/Documents/appium/latest/node_modules/appium/lib/appium.js:387:35)
[HTTP] <-- POST /wd/hub/session 500 26430 ms - 651
[HTTP] 

```

**Comment by KazuCocoa** [comment]
Could you share the full log? Then, please try out the latest Appium flutter driver version

**Comment by KazuCocoa** [comment]
The error message, `Cannot read properties of undefined (reading 'match')`, was probably it failed to find an observatory url. Perhaps recent version's improvement helps it
