### ISSUE TITLE
Appium - Receiving "Url or Uri must start with <scheme>://*" for appium automation of flutter app

### ISSUE THREAD

**Issue by Akshaysk3** [appium-userland/appium-flutter-driver#386]
I am receiving a **UnknownException (500): An unknown server-side error occurred while processing the command. Original error: Url or Uri must start with ://** with 500 response while trying to automate one of the flutter app.

Log file:
[https://gist.github.com/Akshaysk3/0f8b99bd7883f1d8ee67b7f2300de388](url)

`test.setUpAll(() async {
    try {
      driver = await createDriver(
          uri: Uri.parse('http://127.0.0.1:4723/wd/hub/'),
          desired: {
            'platformName': 'ANDROID',
            'appium:app': 'D:/app-dev-debug.apk',
            'appium:deviceName': 'sdk_gphone64_x86_64',
            'appium:UDID': 'emulator-5554',
            'appium:automationName': 'flutter',
            'appium:appPackage': 'in.fello.felloapp.dev',
            'appium:appActivity': 'in.fello.felloapp.MainActivity',
            'appium:autoGrantPermissions': true,
            'appium:fastReset': true,
            'appium:noReset': false,
            'appium:maxRetryCount': 20,
            'appium:ACCEPT_INSECURE_CERTS': true
          },
          spec: WebDriverSpec.Auto);

catch (e) {
      print('Ran into an error $e');
    }
  });
`

**Comment by Akshaysk3** [comment]
I discussed this with Appium support - https://discuss.appium.io/t/appium-url-or-uri-must-start-with-scheme-for-flutter-app/38050
 They reply was to raise an issue here
 
 Below are the capabilities passed;
![Capabilities](https://user-images.githubusercontent.com/117821220/209623890-47c80efc-c895-495d-8185-dfef330de973.png)

**Comment by KazuCocoa** [comment]
The below log means your test code sent open url command with `/sessionXXX`, which is invalid as Appium in general. For example `await driver.get('/sessionXXX')` https://appium.io/docs/en/commands/web/navigation/go-to-url/ in the client code sent it.


```
[HTTP] --> POST /wd/hub/session/62b477f1-663b-499c-9408-e6b5d41fdc7e/url
[HTTP] {"url":"/sessionXXX"}
[W3C (62b477f1)] Encountered internal error running command: Error: Url or Uri must start with ://
[W3C (62b477f1)]     at Object.setUrl (C:\Users\aksha\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\validators.js:17:13)
[W3C (62b477f1)]     at asyncHandler (C:\Users\aksha\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:288:9)
[W3C (62b477f1)]     at C:\Users\aksha\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:423:15
[W3C (62b477f1)]     at Layer.handle [as handle_request] (C:\Users\aksha\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[W3C (62b477f1)]     at next (C:\Users\aksha\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\route.js:137:13)
[W3C (62b477f1)]     at Route.dispatch (C:\Users\aksha\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\route.js:112:3)
[W3C (62b477f1)]     at Layer.handle [as handle_request] (C:\Users\aksha\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[W3C (62b477f1)]     at C:\Users\aksha\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:281:22
[W3C (62b477f1)]     at param (C:\Users\aksha\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:354:14)
[W3C (62b477f1)]     at param (C:\Users\aksha\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:365:14)
[W3C (62b477f1)]     at Function.process_params (C:\Users\aksha\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:410:3)
[W3C (62b477f1)]     at next (C:\Users\aksha\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:275:10)
[W3C (62b477f1)]     at logger (C:\Users\aksha\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\morgan\index.js:144:5)
[W3C (62b477f1)]     at Layer.handle [as handle_request] (C:\Users\aksha\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[W3C (62b477f1)]     at trim_prefix (C:\Users\aksha\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:317:13)
[W3C (62b477f1)]     at C:\Users\aksha\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:284:7
[W3C (62b477f1)]     at Function.process_params (C:\Users\aksha\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:335:12)
[W3C (62b477f1)]     at next (C:\Users\aksha\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:275:10)
[W3C (62b477f1)]     at C:\Users\aksha\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\body-parser\lib\read.js:130:5
[W3C (62b477f1)]     at invokeCallback (C:\Users\aksha\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\raw-body\index.js:224:16)
[W3C (62b477f1)]     at done (C:\Users\aksha\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\raw-body\index.js:213:7)
[W3C (62b477f1)]     at IncomingMessage.onEnd (C:\Users\aksha\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\raw-body\index.js:273:7)
[W3C (62b477f1)]     at IncomingMessage.emit (events.js:322:22)
[W3C (62b477f1)]     at endReadableNT (_stream_readable.js:1187:12)
[W3C (62b477f1)]     at processTicksAndRejections (internal/process/task_queues.js:84:21)
[HTTP] <-- POST /wd/hub/session/62b477f1-663b-499c-9408-e6b5d41fdc7e/url 500 83 ms - 4337
[HTTP] 
```

This driver itself returned 200 ok response as below.

```
[BaseDriver] Event 'newSessionStarted' logged at 1671714942612 (18:45:42 GMT+0530 (India Standard Time))
[W3C (62b477f1)] Cached the protocol value 'W3C' for the new session 62b477f1-663b-499c-9408-e6b5d41fdc7e
[W3C (62b477f1)] Responding to client with driver.createSession() result: {"capabilities":{"shell":false,"allowCors":false,"reboot":false,"ipa":null,"address":"127.0.0.1","port":4723,"basePath":"/wd/hub","keepAliveTimeout":null,"callbackAddress":null,"callbackPort":null,"bootstrapPort":4724,"backendRetries":3,"sessionOverride":false,"launch":false,"logFile":null,"loglevel":"debug","logTimestamp":false,"localTimezone":false,"logNoColors":false,"webhook":null,"safari":false,"defaultDevice":false,"forceIphone":false,"forceIpad":false,"automationTraceTemplatePath":null,"instrumentsPath":null,"nodeconfig":null,"robotAddress":"0.0.0.0","robotPort":-1,"chromedriverExecutable":null,"showConfig":false,"noPermsCheck":false,"enforceStrictCaps":false,"isolateSimDevice":false,"tmpDir":"C:\\Users\\aksha\\AppData\\Local\\Temp","traceDir":null,"debugLogSpacing":false,"suppressKillServer":false,"longStacktrace":false,"webkitDebugProxyPort":27753,"wdaLocalPort":8100,"defaultCapabilities":{},"relaxedSecurityEnabled":true,"allowInsecure":[],"denyInsecure":[],"defaultCommandTimeout":60,"keepArtifact...
[HTTP] <-- POST /wd/hub
```

**Comment by Akshaysk3** [comment]
Got it thanks, not getting this anymore
