### ISSUE TITLE
Flutter App keeps crashing

### ISSUE THREAD

**Issue by iamsobowale** [appium-userland/appium-flutter-driver#403]
When i set 'automationName': 'flutter', the app keeps crashing and i get this error after few retries

2023-01-23T09:45:54.590Z WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Cannot read properties of undefined (reading 'match')
2023-01-23T09:45:54.591Z INFO webdriver: Retrying 3/3
2023-01-23T09:45:54.592Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session
2023-01-23T09:45:54.592Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      automationName: 'flutter',
      platformName: 'Android',
      deviceName: 'M2010J19SG',
      app: 'C:\\Users\\iamso\\Desktop\\bbbf/app/app-dev-debug.apk'
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    automationName: 'flutter',
    platformName: 'Android',
    deviceName: 'M2010J19SG',
    app: 'C:\\Users\\iamso\\Desktop\\bbbf/app/app-dev-debug.apk'
    at async WebDriver.newSession (file:///C:/Users/iamso/Desktop/bbbf/node_modules/webdriver/build/index.js:24:45)    at async remote (file:///C:/Users/iamso/Desktop/bbbf/node_modules/webdriverio/build/index.js:48:22)
    at async main (C:\Users\iamso\Desktop\bbbf\test.js:21:20)file:///C:/Users/iamso/Desktop/bbbf/node_modules/webdriver/build/utils.js:68        throw new Error('Failed to create session.\n' + message);
              ^

Error: Failed to create session.
An unknown server-side error occurred while processing the command. Original error: Cannot read properties of undefined (reading 'match')
    at startWebDriverSession (file:///C:/Users/iamso/Desktop/bbbf/node_modules/webdriver/build/utils.js:68:15)     
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)    at async WebDriver.newSession (file:///C:/Users/iamso/Desktop/bbbf/node_modules/webdriver/build/index.js:24:45)    at async remote (file:///C:/Users/iamso/Desktop/bbbf/node_modules/webdriverio/build/index.js:48:22)
    at async main (C:\Users\iamso\Desktop\bbbf\test.js:21:20)

Node.js v19.4.0

But if i set it to 'automationName': 'appium', i get method not implenmented

**Comment by KazuCocoa** [comment]
Please use the latest driver with Appium 2.0. The error message indicates your environment is not the latest one
