### ISSUE TITLE
Run flutter App On Browserstack Remotely

### ISSUE THREAD

**Issue by iamsobowale** [appium-userland/appium-flutter-driver#405]
I have been able to run my flutter app locally but trying to look for a way to run it remotly on browserstack, most articles are for running apps that are not flutter

var capabilities = {
'bstack:options' : {
"osVersion" : "10.0",
"deviceName" : "Samsung Galaxy S20",
"projectName" : "AppName",
"buildName" : "V1",
"sessionName" : "b",
"local" : "false",
"userName" : "USERNAME",
"accessKey" : "ACCESS_KEY",
},
"browserName" : "chrome",
}

Got this Capabilities from browserstack and this was the error i was getting

2023-01-27T07:26:08.409Z INFO devtools:puppeteer: Initiate new session using the DevTools protocol
2023-01-27T07:26:08.412Z INFO devtools: Launch Google Chrome (undefined) with flags: --enable-automation --disable-popup-blocking --disable-extensions --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-first-run --no-default-browser-check --disable-hang-monitor --disable-prompt-on-repost --disable-client-side-phishing-detection --password-store=basic --use-mock-keychain --disable-component-extensions-with-background-pages --disable-breakpad --disable-dev-shm-usage --disable-ipc-flooding-protection --disable-renderer-backgrounding --force-fieldtrials=*BackgroundTracing/default/ --enable-features=NetworkService,NetworkServiceInProcess --disable-features=site-per-process,TranslateUI,BlinkGenPropertyTrees --window-position=0,0 --window-size=1200,900
2023-01-27T07:26:08.953Z INFO devtools: Connect Puppeteer with browser on port 65076
Hello
2023-01-27T07:26:09.110Z INFO devtools: COMMAND executeScript("flutter:checkHealth", <object>)
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Evaluation failed: ReferenceError: checkHealth is not defined
    at eval (eval at <anonymous> (:3:20), <anonymous>:1:9)
    at pptr://__puppeteer_evaluation_script__:3:20
Error: Evaluation failed: ReferenceError: checkHealth is not defined
    at eval (eval at <anonymous> (:3:20), <anonymous>:1:9)
    at pptr://__puppeteer_evaluation_script__:3:20
    at ExecutionContext._ExecutionContext_evaluate (file:///C:/Users/iamso/Desktop/bbbf/node_modules/puppeteer-core/lib/esm/puppeteer/common/ExecutionContext.js:225:15)      
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ElementHandle.$eval (file:///C:/Users/iamso/Desktop/bbbf/node_modules/puppeteer-core/lib/esm/puppeteer/common/ElementHandle.js:138:24)
    at async DevToolsDriver.executeScript (file:///C:/Users/iamso/Desktop/bbbf/node_modules/devtools/build/commands/executeScript.js:34:20)
    at async Browser.wrappedCommand (file:///C:/Users/iamso/Desktop/bbbf/node_modules/devtools/build/devtoolsdriver.js:127:26)
    at async Browser.wrapCommandFn (file:///C:/Users/iamso/Desktop/bbbf/node_modules/@wdio/utils/build/shim.js:72:29)
    at async Browser.wrapCommandFn (file:///C:/Users/iamso/Desktop/bbbf/node_modules/@wdio/utils/build/shim.js:72:29)
    at async main (C:\Users\iamso\Desktop\bbbf\test.js:47:24)

Node.js v19.4.0

**Comment by KazuCocoa** [comment]
Please ask their customer support. This driver's availability depends on cloud vendors.
