### ISSUE TITLE
getElementText is not working

### ISSUE THREAD

**Issue by SanusiWasiu** [appium-userland/appium-flutter-driver#434]
Execution of 1 workers started at 2023-03-16T13:37:02.425Z

2023-03-16T13:37:02.443Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-03-16T13:37:08.475Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-03-16T13:37:08.477Z INFO @wdio/local-runner: Start worker 0-0 with arg: 
[0-0] 2023-03-16T13:37:08.899Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in Android - C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\test\specs\android\login.e2e.js
[0-0] 2023-03-16T13:37:09.344Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2023-03-16T13:37:09.398Z INFO webdriver: [POST] http://localhost:4723/session
[0-0] 2023-03-16T13:37:09.398Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       platformName: 'Android',
[0-0]       'appium:deviceName': 'Pop',
[0-0]       'appium:platformVersion': '11.0',
[0-0]       'appium:automationName': 'Flutter',
[0-0]       'appium:app': 'app/android/app-debug.apk',
[0-0]       'appium:autoGrantPermissions': true,
[0-0]       acceptInsecureCerts: true
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     platformName: 'Android',
[0-0]     'appium:deviceName': 'Pop',
[0-0]     'appium:platformVersion': '11.0',
[0-0]     'appium:automationName': 'Flutter',
[0-0]     'appium:app': 'app/android/app-debug.apk',
[0-0]     'appium:autoGrantPermissions': true,
[0-0]     acceptInsecureCerts: true
[0-0]   }
[0-0] }
[0-0] 2023-03-16T13:37:29.683Z INFO webdriver: COMMAND executeScript("flutter:checkHealth", <object>)
[0-0] 2023-03-16T13:37:29.683Z INFO webdriver: [POST] http://localhost:4723/session/9e4ec97e-4196-4afe-a872-a26b066453be/execute/sync
[0-0] 2023-03-16T13:37:29.684Z INFO webdriver: DATA { script: 'flutter:checkHealth', args: [] }
[0-0] 2023-03-16T13:37:29.747Z INFO webdriver: RESULT ok
[0-0] 2023-03-16T13:37:29.748Z INFO webdriver: COMMAND executeScript("flutter:clearTimeline", <object>)
[0-0] 2023-03-16T13:37:29.750Z INFO webdriver: [POST] http://localhost:4723/session/9e4ec97e-4196-4afe-a872-a26b066453be/execute/sync
[0-0] 2023-03-16T13:37:29.750Z INFO webdriver: DATA { script: 'flutter:clearTimeline', args: [] }
[0-0] 2023-03-16T13:37:29.770Z INFO webdriver: COMMAND executeScript("flutter:forceGC", <object>)
[0-0] 2023-03-16T13:37:29.770Z INFO webdriver: [POST] http://localhost:4723/session/9e4ec97e-4196-4afe-a872-a26b066453be/execute/sync
[0-0] 2023-03-16T13:37:29.770Z INFO webdriver: DATA { script: 'flutter:forceGC', args: [] }
[0-0] 2023-03-16T13:37:29.868Z INFO webdriver: COMMAND executeScript("flutter:waitFor", <object>)
[0-0] 2023-03-16T13:37:29.869Z INFO webdriver: [POST] http://localhost:4723/session/9e4ec97e-4196-4afe-a872-a26b066453be/execute/sync
[0-0] 2023-03-16T13:37:29.870Z INFO webdriver: DATA {
[0-0]   script: 'flutter:waitFor',
[0-0]   args: [
[0-0]     'eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiR2V0IFN0YXJ0ZWQiLCJrZXlWYWx1ZVR5cGUiOiJTdHJpbmcifQ'     
[0-0]   ]
[0-0] }
[0-0] 2023-03-16T13:37:29.947Z WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Cannot execute command waitFor, server reponse {
[0-0]   "isError": true,
[0-0]   "response": "Uncaught extension error while executing waitFor: 'package:flutter_driver/src/extension/extension.dart': Failed assertion: line 366 pos 14: 'WidgetsBinding.instance.isRootWidgetAttached || !command.requiresRootWidgetAttached': No root widget is attached; have you remembered to call runApp()?\n#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)\n#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)\n#2      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:366:14)\n#3      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:855:32)\n<asynchronous suspension>\n",
[0-0]   "type": "_extensionType",
[0-0]   "method": "ext.flutter.driver"
[0-0] }
[0-0] 2023-03-16T13:37:29.947Z INFO webdriver: Retrying 1/3
[0-0] 2023-03-16T13:37:29.947Z INFO webdriver: [POST] http://localhost:4723/session/9e4ec97e-4196-4afe-a872-a26b066453be/execute/sync
[0-0] 2023-03-16T13:37:29.947Z INFO webdriver: DATA {
[0-0]   script: 'flutter:waitFor',
[0-0]   args: [
[0-0]     'eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiR2V0IFN0YXJ0ZWQiLCJrZXlWYWx1ZVR5cGUiOiJTdHJpbmcifQ'     
[0-0]   ]
[0-0] }
[0-0] 2023-03-16T13:37:35.534Z INFO webdriver: RESULT eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiR2V0IFN0YXJ0ZWQiLCJrZXlWYWx1ZVR5cGUiOiJTdHJpbmcifQ
[0-0] 2023-03-16T13:37:35.536Z INFO webdriver: COMMAND elementClick("eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiR2V0IFN0YXJ0ZWQiLCJrZXlWYWx1ZVR5cGUiOiJTdHJpbmcifQ")
[0-0] 2023-03-16T13:37:35.537Z INFO webdriver: [POST] http://localhost:4723/session/9e4ec97e-4196-4afe-a872-a26b066453be/element/eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiR2V0IFN0YXJ0ZWQiLCJrZXlWYWx1ZVR5cGUiOiJTdHJpbmcifQ/click
[0-0] 2023-03-16T13:37:36.017Z INFO webdriver: RESULT {}
[0-0] 2023-03-16T13:37:36.022Z INFO webdriver: COMMAND elementClick("eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiSSBoYXZlIGFuIEFSTSBhY2NvdW50Iiwia2V5VmFsdWVUeXBlIjoiU3RyaW5nIn0")
[0-0] 2023-03-16T13:37:36.022Z INFO webdriver: [POST] http://localhost:4723/session/9e4ec97e-4196-4afe-a872-a26b066453be/element/eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiSSBoYXZlIGFuIEFSTSBhY2NvdW50Iiwia2V5VmFsdWVUeXBlIjoiU3RyaW5nIn0/click
[0-0] 2023-03-16T13:37:36.602Z INFO webdriver: RESULT {}
[0-0] 2023-03-16T13:37:46.605Z INFO webdriver: COMMAND elementClick("<Screenshot[base64]>")
[0-0] 2023-03-16T13:37:46.606Z INFO webdriver: [POST] http://localhost:4723/session/9e4ec97e-4196-4afe-a872-a26b066453be/element/eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiRW1haWwgQWRkcmVzcyIsImtleVZhbHVlVHlwZSI6IlN0cmluZyJ9/click       
[0-0] 2023-03-16T13:37:46.878Z INFO webdriver: RESULT {}
[0-0] 2023-03-16T13:37:46.882Z INFO webdriver: COMMAND elementSendKeys("<Screenshot[base64]>", "jim@yopmail.com")
[0-0] 2023-03-16T13:37:46.883Z INFO webdriver: [POST] http://localhost:4723/session/9e4ec97e-4196-4afe-a872-a26b066453be/element/eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiRW1haWwgQWRkcmVzcyIsImtleVZhbHVlVHlwZSI6IlN0cmluZyJ9/value       
[0-0] 2023-03-16T13:37:46.883Z INFO webdriver: DATA { text: 'jim@yopmail.com' }
[0-0] 2023-03-16T13:37:47.227Z INFO webdriver: COMMAND getElementText("<Screenshot[base64]>")
[0-0] 2023-03-16T13:37:47.228Z INFO webdriver: [GET] http://localhost:4723/session/9e4ec97e-4196-4afe-a872-a26b066453be/element/eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiRW1haWwgQWRkcmVzcyIsImtleVZhbHVlVHlwZSI6IlN0cmluZyJ9/text
[0-0] 2023-03-16T13:37:47.315Z INFO webdriver: RESULT jim@yopmail.com
[0-0] 2023-03-16T13:37:47.318Z INFO webdriver: COMMAND elementClick("eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiQ29udGludWUiLCJrZXlWYWx1ZVR5cGUiOiJTdHJpbmcifQ")
[0-0] 2023-03-16T13:37:47.318Z INFO webdriver: [POST] http://localhost:4723/session/9e4ec97e-4196-4afe-a872-a26b066453be/element/eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiQ29udGludWUiLCJrZXlWYWx1ZVR5cGUiOiJTdHJpbmcifQ/click
[0-0] 2023-03-16T13:37:47.404Z INFO webdriver: RESULT {}
[0-0] 2023-03-16T13:37:47.409Z INFO webdriver: COMMAND executeScript("flutter:waitFor", <object>)
[0-0] 2023-03-16T13:37:47.409Z INFO webdriver: [POST] http://localhost:4723/session/9e4ec97e-4196-4afe-a872-a26b066453be/execute/sync
[0-0] 2023-03-16T13:37:47.409Z INFO webdriver: DATA {
[0-0]   script: 'flutter:waitFor',
[0-0]   args: [
[0-0]     'eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiUGFzc3dvcmQiLCJrZXlWYWx1ZVR5cGUiOiJTdHJpbmcifQ'
[0-0]   ]
[0-0] }
[0-0] 2023-03-16T13:37:49.369Z INFO webdriver: RESULT eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiUGFzc3dvcmQiLCJrZXlWYWx1ZVR5cGUiOiJTdHJpbmcifQ
[0-0] 2023-03-16T13:37:49.373Z INFO webdriver: COMMAND elementClick("eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiUGFzc3dvcmQiLCJrZXlWYWx1ZVR5cGUiOiJTdHJpbmcifQ")
[0-0] 2023-03-16T13:37:49.373Z INFO webdriver: [POST] http://localhost:4723/session/9e4ec97e-4196-4afe-a872-a26b066453be/element/eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiUGFzc3dvcmQiLCJrZXlWYWx1ZVR5cGUiOiJTdHJpbmcifQ/click
[0-0] 2023-03-16T13:37:49.462Z INFO webdriver: RESULT {}
[0-0] 2023-03-16T13:37:49.466Z INFO webdriver: COMMAND elementSendKeys("eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiUGFzc3dvcmQiLCJrZXlWYWx1ZVR5cGUiOiJTdHJpbmcifQ", "Welcome123@")
[0-0] 2023-03-16T13:37:49.466Z INFO webdriver: [POST] http://localhost:4723/session/9e4ec97e-4196-4afe-a872-a26b066453be/element/eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiUGFzc3dvcmQiLCJrZXlWYWx1ZVR5cGUiOiJTdHJpbmcifQ/value
[0-0] 2023-03-16T13:37:49.466Z INFO webdriver: DATA { text: 'Welcome123@' }
[0-0] 2023-03-16T13:37:49.766Z INFO webdriver: COMMAND elementClick("eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiQ29udGludWUiLCJrZXlWYWx1ZVR5cGUiOiJTdHJpbmcifQ")
[0-0] 2023-03-16T13:37:49.766Z INFO webdriver: [POST] http://localhost:4723/session/9e4ec97e-4196-4afe-a872-a26b066453be/element/eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiQ29udGludWUiLCJrZXlWYWx1ZVR5cGUiOiJTdHJpbmcifQ/click
[0-0] 2023-03-16T13:37:49.871Z INFO webdriver: RESULT {}
[0-0] 2023-03-16T13:37:49.874Z INFO webdriver: COMMAND executeScript("flutter:waitFor", <object>)
[0-0] 2023-03-16T13:37:49.875Z INFO webdriver: [POST] http://localhost:4723/session/9e4ec97e-4196-4afe-a872-a26b066453be/execute/sync
[0-0] 2023-03-16T13:37:49.875Z INFO webdriver: DATA {
[0-0]   script: 'flutter:waitFor',
[0-0]   args: [
[0-0]     'eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiVG9wIHVwIiwia2V5VmFsdWVUeXBlIjoiU3RyaW5nIn0'
[0-0]   ]
[0-0] }
[0-0] 2023-03-16T13:38:53.690Z INFO webdriver: RESULT eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiVG9wIHVwIiwia2V5VmFsdWVUeXBlIjoiU3RyaW5nIn0
[0-0] 2023-03-16T13:38:53.692Z INFO webdriver: COMMAND getElementText("eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiVG9wIHVwIiwia2V5VmFsdWVUeXBlIjoiU3RyaW5nIn0")
[0-0] 2023-03-16T13:38:53.693Z INFO webdriver: [GET] http://localhost:4723/session/9e4ec97e-4196-4afe-a872-a26b066453be/element/eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiVG9wIHVwIiwia2V5VmFsdWVUeXBlIjoiU3RyaW5nIn0/text
[0-0] 2023-03-16T13:38:53.740Z WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Cannot execute command get_text, server reponse {
[0-0]   "isError": true,
[0-0]   "response": "Uncaught extension error while executing get_text: Unsupported operation: Type Column is currently not supported by getText\n#0      CommandHandlerFactory._getText (package:flutter_driver/src/common/handler_factory.dart:418:7)\n<asynchronous suspension>\n#1      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:372:31)\n<asynchronous suspension>\n#2      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:855:18)\n<asynchronous suspension>\n",
[0-0]   "type": "_extensionType",
[0-0]   "method": "ext.flutter.driver"
[0-0] }
[0-0] 2023-03-16T13:38:53.740Z INFO webdriver: Retrying 1/3
[0-0] 2023-03-16T13:38:53.740Z INFO webdriver: [GET] http://localhost:4723/session/9e4ec97e-4196-4afe-a872-a26b066453be/element/eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiVG9wIHVwIiwia2V5VmFsdWVUeXBlIjoiU3RyaW5nIn0/text
[0-0] 2023-03-16T13:38:53.787Z WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Cannot execute command get_text, server reponse {
[0-0]   "isError": true,
[0-0]   "response": "Uncaught extension error while executing get_text: Unsupported operation: Type Column is currently not supported by getText\n#0      CommandHandlerFactory._getText (package:flutter_driver/src/common/handler_factory.dart:418:7)\n<asynchronous suspension>\n#1      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:372:31)\n<asynchronous suspension>\n#2      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:855:18)\n<asynchronous suspension>\n",
[0-0]   "type": "_extensionType",
[0-0]   "method": "ext.flutter.driver"
[0-0] }
[0-0] 2023-03-16T13:38:53.788Z INFO webdriver: Retrying 2/3
[0-0] 2023-03-16T13:38:53.788Z INFO webdriver: [GET] http://localhost:4723/session/9e4ec97e-4196-4afe-a872-a26b066453be/element/eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiVG9wIHVwIiwia2V5VmFsdWVUeXBlIjoiU3RyaW5nIn0/text
[0-0] 2023-03-16T13:38:53.828Z WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Cannot execute command get_text, server reponse {
[0-0]   "isError": true,
[0-0]   "response": "Uncaught extension error while executing get_text: Unsupported operation: Type Column is currently not supported by getText\n#0      CommandHandlerFactory._getText (package:flutter_driver/src/common/handler_factory.dart:418:7)\n<asynchronous suspension>\n#1      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:372:31)\n<asynchronous suspension>\n#2      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:855:18)\n<asynchronous suspension>\n",
[0-0]   "type": "_extensionType",
[0-0]   "method": "ext.flutter.driver"
[0-0] }
[0-0] 2023-03-16T13:38:53.828Z INFO webdriver: Retrying 3/3
[0-0] 2023-03-16T13:38:53.829Z INFO webdriver: [GET] http://localhost:4723/session/9e4ec97e-4196-4afe-a872-a26b066453be/element/eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiVG9wIHVwIiwia2V5VmFsdWVUeXBlIjoiU3RyaW5nIn0/text
[0-0] 2023-03-16T13:38:53.853Z ERROR webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: Cannot execute command get_text, server reponse {
[0-0]   "isError": true,
[0-0]   "response": "Uncaught extension error while executing get_text: Unsupported operation: Type Column is currently not supported by getText\n#0      CommandHandlerFactory._getText (package:flutter_driver/src/common/handler_factory.dart:418:7)\n<asynchronous suspension>\n#1      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:372:31)\n<asynchronous suspension>\n#2      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:855:18)\n<asynchronous suspension>\n",
[0-0]   "type": "_extensionType",
[0-0]   "method": "ext.flutter.driver"
[0-0] }
[0-0] 2023-03-16T13:38:53.863Z INFO webdriver: COMMAND takeScreenshot()
[0-0] 2023-03-16T13:38:53.863Z INFO webdriver: [GET] http://localhost:4723/session/9e4ec97e-4196-4afe-a872-a26b066453be/screenshot
[0-0] 2023-03-16T13:38:54.368Z INFO webdriver: RESULT iVBORw0KGgoAAAANSUhEUgAAAtAAAAXgCAYAAAB4in6/AAAAAXNSR0IArs4c6...
[0-0] unknown error in "Login Test.ARM One Account.should login with valid email and password"
unknown error: An unknown server-side error occurred while processing the command. Original error: Cannot execute command get_text, server reponse {
  "isError": true,
  "response": "Uncaught extension error while executing get_text: Unsupported operation: Type Column is currently not supported by getText\n#0      CommandHandlerFactory._getText (package:flutter_driver/src/common/handler_factory.dart:418:7)\n<asynchronous suspension>\n#1      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:372:31)\n<asynchronous suspension>\n#2      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:855:18)\n<asynchronous suspension>\n",
  "type": "_extensionType",
  "method": "ext.flutter.driver"
}
    at getErrorFromResponseBody (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriver\build\utils.js:198:12)
    at NodeJSRequest._request (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriver\build\request\index.js:166:60)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Browser.wrapCommandFn (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\@wdio\utils\build\shim.js:137:29)
    at LoginScreen.assertLogin (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\test\screenobjects\android\login.screen.js:55:28)
    at Context.<anonymous> (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\test\specs\android\login.e2e.js:36:13)
[0-0] 2023-03-16T13:38:54.377Z INFO webdriver: COMMAND deleteSession()
[0-0] 2023-03-16T13:38:54.378Z INFO webdriver: [DELETE] http://localhost:4723/session/9e4ec97e-4196-4afe-a872-a26b066453be     
[0-0] 2023-03-16T13:38:55.014Z INFO webdriver: [POST] http://localhost:4723/session
[0-0] 2023-03-16T13:38:55.014Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       platformName: 'Android',
[0-0]       'appium:deviceName': 'Pop',
[0-0]       'appium:platformVersion': '11.0',
[0-0]       'appium:automationName': 'Flutter',
[0-0]       'appium:app': 'app/android/app-debug.apk',
[0-0]       'appium:autoGrantPermissions': true,
[0-0]       acceptInsecureCerts: true
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     platformName: 'Android',
[0-0]     'appium:deviceName': 'Pop',
[0-0]     'appium:platformVersion': '11.0',
[0-0]     'appium:automationName': 'Flutter',
[0-0]     'appium:app': 'app/android/app-debug.apk',
[0-0]     'appium:autoGrantPermissions': true,
[0-0]     acceptInsecureCerts: true
[0-0]   }
[0-0] }
[0-0] 2023-03-16T13:39:13.619Z INFO webdriver: COMMAND deleteSession()
[0-0] 2023-03-16T13:39:13.619Z INFO webdriver: [DELETE] http://localhost:4723/session/ceef7250-631e-4d98-9c33-2069f9325cdd
[0-0] FAILED in Android - C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\test\specs\android\login.e2e.js
2023-03-16T13:39:14.152Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-03-16T13:39:14.153Z INFO @wdio/cli:launcher: Run onComplete hook
.............................
[Pop Android 11.0 #0-0] An unknown server-side error occurred while processing the command. Original error: Cannot execute command get_text, server reponse {
  "isError": true,
  "response": "Uncaught extension error while executing get_text: Unsupported operation: Type Column is currently not supported by getText\n#0      CommandHandlerFactory._getText (package:flutter_driver/src/common/handler_factory.dart:418:7)\n<asynchronous suspension>\n#1      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:372:31)\n<asynchronous suspension>\n#2      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:855:18)\n<asynchronous suspension>\n",
  "type": "_extensionType",
  "method": "ext.flutter.driver"
}
[Pop Android 11.0 #0-0] unknown error: An unknown server-side error occurred while processing the command. Original error: Cannot execute command get_text, server reponse {
[Pop Android 11.0 #0-0]   "isError": true,
[Pop Android 11.0 #0-0]   "response": "Uncaught extension error while executing get_text: Unsupported operation: Type Column is currently not supported by getText\n#0      CommandHandlerFactory._getText (package:flutter_driver/src/common/handler_factory.dart:418:7)\n<asynchronous suspension>\n#1      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:372:31)\n<asynchronous suspension>\n#2      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:855:18)\n<asynchronous suspension>\n",
[Pop Android 11.0 #0-0]   "type": "_extensionType",
[Pop Android 11.0 #0-0]   "method": "ext.flutter.driver"
[Pop Android 11.0 #0-0] }
[Pop Android 11.0 #0-0]     at getErrorFromResponseBody (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriver\build\utils.js:198:12)
[Pop Android 11.0 #0-0]     at NodeJSRequest._request (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriver\build\request\index.js:166:60)
[Pop Android 11.0 #0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[Pop Android 11.0 #0-0]     at Browser.wrapCommandFn (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\@wdio\utils\build\shim.js:137:29)
[Pop Android 11.0 #0-0]     at LoginScreen.assertLogin (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\test\screenobjects\android\login.screen.js:55:28)
[Pop Android 11.0 #0-0]     at Context.<anonymous> (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\test\specs\android\login.e2e.js:36:13)

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:02:11

2023-03-16T13:39:14.160Z INFO @wdio/local-runner: Shutting down spawned worker
2023-03-16T13:39:14.418Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-03-16T13:39:14.419Z INFO @wdio/local-runner: shutting down

**Comment by KazuCocoa** [comment]
This means the command did not work for the element, but it is by Flutter/Dart VM itself. Not by this driver. Perhaps https://api.flutter.dev/flutter/flutter_driver/flutter_driver-library.html related thing.

```
[Pop Android 11.0 #0-0] An unknown server-side error occurred while processing the command. Original error: Cannot execute command get_text, server reponse {
"isError": true,
"response": "Uncaught extension error while executing get_text: Unsupported operation: Type Column is currently not supported by getText\n#0 CommandHandlerFactory._getText (package:flutter_driver/src/common/handler_factory.dart:418:7)\n\n#1 FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:372:31)\n\n#2 BindingBase.registerServiceExtension. (package:flutter/src/foundation/binding.dart:855:18)\n\n",
"type": "_extensionType",
"method": "ext.flutter.driver"
}
```
