### ISSUE TITLE
scroll  function issue : : input is invalid 

### ISSUE THREAD

**Issue by wsfcsk** [appium-userland/appium-flutter-driver#447]
Hi  team 
I tried to use this for scrolling :
application.execute_script('flutter:scrollUntilVisible', self._element_finder.find(application,"type=ListView"), {"item":self._element_finder.find(application,locator), "dxScroll": 90, "dyScroll": 400,"waitTimeoutMilliseconds": 20000})

the error is ：
[debug] [FlutterDriver] Executing Flutter driver command 'execute'
uncaughtException: input is invalid {"element-6066-11e4-a52e-4f735466cecf":"eyJmaW5kZXJUeXBlIjoiQnlTZW1hbnRpY3NMYWJlbCIsImlzUmVnRXhwIjpmYWxzZSwibGFiZWwiOiJkb2N0b3JzUGFnZV9JbmtXZWxsX2RpZF85MjM1OTYifQ=="}
Error: input is invalid {"element-6066-11e4-a52e-4f735466cecf":"eyJmaW5kZXJUeXBlIjoiQnlTZW1hbnRpY3NMYWJlbCIsImlzUmVnRXhwIjpmYWxzZSwibGFiZWwiOiJkb2N0b3JzUGFnZV9JbmtXZWxsX2RpZF85MjM1OTYifQ=="}
    at decode (/Users/han.xiao/.appium/node_modules/finder/nodejs/lib/base64url.ts:15:11)
    at deserialize (/Users/han.xiao/.appium/node_modules/finder/nodejs/lib/deserializer.ts:4:20)
    at FlutterDriver.executeElementCommand (/Users/han.xiao/.appium/node_modules/appium-flutter-driver/lib/sessions/observatory.ts:172:52)
    at /Users/han.xiao/.appium/node_modules/appium-flutter-driver/lib/commands/execute/wait.ts:20:14
    at scrollUntilVisible (/Users/han.xiao/.appium/node_modules/appium-flutter-driver/lib/commands/execute/scroll.ts:103:18)
    at FlutterDriver.execute (/Users/han.xiao/.appium/node_modules/appium-flutter-driver/lib/commands/execute.ts:56:32)
    at commandExecutor (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:122:18)
    at /opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:171:12
    at AsyncLock._promiseTry (/opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:304:31)
    at exec (/opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:170:9)
    at AsyncLock.acquire (/opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:187:3)
    at FlutterDriver.executeCommand (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:138:39)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at FlutterDriver.executeCommand (/Users/han.xiao/.appium/node_modules/appium-flutter-driver/lib/driver.ts:139:16)
    at defaultBehavior (/opt/homebrew/lib/node_modules/appium/lib/appium.js:673:14)
    at AppiumDriver.executeWrappedCommand (/opt/homebrew/lib/node_modules/appium/lib/appium.js:763:16)
    at AppiumDriver.executeCommand (/opt/homebrew/lib/node_modules/appium/lib/appium.js:685:17)
    at asyncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:387:19)

could you help this ?
thanks in advanced !

**Comment by KazuCocoa** [comment]
Could you share the full appium server log as GIST?

**Comment by ostandsouza** [comment]
@KazuCocoa This is related to not just scrolling, whenever i tried with any driver.executeScript(flutter commands) this is happening.

Below is my code:
```
//Page
public class Tap extends FlutterBase {
    public AppiumDriver driver;

    public Tap(AppiumDriver driver){
        super(driver);
        PageFactory.initElements(new AppiumFieldDecorator(driver),this);
        this.driver = driver;
    }

    public void tapAction(){
        find.bySemanticsLabel("switch").click();
        driver.executeScript("flutter:waitFor", find.bySemanticsLabel("Tap Successful"), 30);
    }
}

public class Landing extends FlutterBase {

    public AppiumDriver driver;

    public Landing(AppiumDriver driver)  {
        super(driver);
        PageFactory.initElements(new AppiumFieldDecorator(driver), this);
        this.driver = driver;
        driver.executeScript("flutter:waitForFirstFrame");
    }

    public void gotoTap() {
        find.bySemanticsLabel("Tap").click();
    }
}

//Flutter methods
public class FlutterBase {

    public AppiumDriver driver;
    public FlutterFinder find;

    public FlutterBase(AppiumDriver driver) {
        this.driver = driver;
        this.find = new FlutterFinder(this.driver);
    }
    
        public boolean isVisisble(FlutterElement element) {
          try{
                  driver.executeScript("flutter:waitFor", element, 30);    **//here it is failing**
                  return true;
              } catch (Exception ignored) {
                  System.out.println("Inside exception " + ignored);
                  return false;
              }
      }
}

//testcase
public class TapTest extends TestBase{

    public Tap tap;
    public Landing landing;

    @BeforeMethod
    public void init() {
        landing = new Landing((AppiumDriver)driver);
        tap= new Tap((AppiumDriver)driver);
    }

    @Test
    public void tapTestcase() {
        landing.gotoTap();
        tap.tapAction();
    }
}
```
  
I have attached appium logs for this session here 
[appium_log.txt](https://github.com/appium-userland/appium-flutter-driver/files/11316059/appium_log.txt)
appium -v (2.0.0-beta.56)
flutter driver -v (flutter@1.7.2)

**Comment by KazuCocoa** [comment]
`flutter:waitFor`'s first argument should be a finder. https://github.com/appium-userland/appium-flutter-driver

**Comment by ostandsouza** [comment]
@KazuCocoa I'm assuming this is correct format
`driver.executeScript("flutter:waitFor", find.bySemanticsLabel("Tap Successful"), 30);`
i have referred 
https://github.com/appium-userland/appium-flutter-driver/blob/main/example/java/src/test/java/example/appium/FlutterTest.java
https://api.flutter.dev/flutter/flutter_driver/FlutterDriver/waitFor.html
Kindly feel free to correct me.

**Comment by wsfcsk** [comment]
hi  here is the full log :
===================================
[debug] [FlutterDriver@8df0 (1d24424c)] Calling AppiumDriver.execute() with args: ["flutter:scrollUntilVisible",[{"element-6066-11e4-a52e-4f735466cecf":"eyJmaW5kZXJUeXBlIjoiQnlUeXBlIiwidHlwZSI6Ikxpc3RWaWV3In0="},{"item":{"element-6066-11e4-a52e-4f735466cecf":"eyJmaW5kZXJUeXBlIjoiQnlTZW1hbnRpY3NMYWJlbCIsImlzUmVnRXhwIjpmYWxzZSwibGFiZWwiOiJkb2N0b3JzUGFnZV9JbmtXZWxsX2RpZF8xMzI0MjkyIn0="},"dxScroll":90,"dyScroll":400,"waitTimeoutMilliseconds":20000}],"1d24424c-480c-4aed-af72-429e906347f4"]
[debug] [FlutterDriver] Executing Flutter driver command 'execute'
uncaughtException: input is invalid {"element-6066-11e4-a52e-4f735466cecf":"eyJmaW5kZXJUeXBlIjoiQnlTZW1hbnRpY3NMYWJlbCIsImlzUmVnRXhwIjpmYWxzZSwibGFiZWwiOiJkb2N0b3JzUGFnZV9JbmtXZWxsX2RpZF8xMzI0MjkyIn0="}
Error: input is invalid {"element-6066-11e4-a52e-4f735466cecf":"eyJmaW5kZXJUeXBlIjoiQnlTZW1hbnRpY3NMYWJlbCIsImlzUmVnRXhwIjpmYWxzZSwibGFiZWwiOiJkb2N0b3JzUGFnZV9JbmtXZWxsX2RpZF8xMzI0MjkyIn0="}
    at decode (/Users/han.xiao/.appium/node_modules/finder/nodejs/lib/base64url.ts:15:11)
    at deserialize (/Users/han.xiao/.appium/node_modules/finder/nodejs/lib/deserializer.ts:4:20)
    at FlutterDriver.executeElementCommand (/Users/han.xiao/.appium/node_modules/appium-flutter-driver/lib/sessions/observatory.ts:172:52)
    at /Users/han.xiao/.appium/node_modules/appium-flutter-driver/lib/commands/execute/wait.ts:20:14
    at scrollUntilVisible (/Users/han.xiao/.appium/node_modules/appium-flutter-driver/lib/commands/execute/scroll.ts:103:18)
    at FlutterDriver.execute (/Users/han.xiao/.appium/node_modules/appium-flutter-driver/lib/commands/execute.ts:56:32)
    at commandExecutor (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:122:18)
    at /opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:171:12
    at AsyncLock._promiseTry (/opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:304:31)
    at exec (/opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:170:9)
    at AsyncLock.acquire (/opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:187:3)
    at FlutterDriver.executeCommand (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:138:39)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at FlutterDriver.executeCommand (/Users/han.xiao/.appium/node_modules/appium-flutter-driver/lib/driver.ts:139:16)
    at defaultBehavior (/opt/homebrew/lib/node_modules/appium/lib/appium.js:673:14)
    at AppiumDriver.executeWrappedCommand (/opt/homebrew/lib/node_modules/appium/lib/appium.js:763:16)
    at AppiumDriver.executeCommand (/opt/homebrew/lib/node_modules/appium/lib/appium.js:685:17)
    at asyncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:387:19)
[debug] [FlutterDriver@8df0 (1d24424c)] Encountered internal error running command: Error: input is invalid {"element-6066-11e4-a52e-4f735466cecf":"eyJmaW5kZXJUeXBlIjoiQnlUeXBlIiwidHlwZSI6Ikxpc3RWaWV3In0="}
[debug] [FlutterDriver@8df0 (1d24424c)]     at decode (/Users/han.xiao/.appium/node_modules/finder/nodejs/lib/base64url.ts:15:11)
[debug] [FlutterDriver@8df0 (1d24424c)]     at deserialize (/Users/han.xiao/.appium/node_modules/finder/nodejs/lib/deserializer.ts:4:20)
[debug] [FlutterDriver@8df0 (1d24424c)]     at FlutterDriver.executeElementCommand (/Users/han.xiao/.appium/node_modules/appium-flutter-driver/lib/sessions/observatory.ts:172:52)
[debug] [FlutterDriver@8df0 (1d24424c)]     at scroll (/Users/han.xiao/.appium/node_modules/appium-flutter-driver/lib/commands/execute/scroll.ts:34:21)
[debug] [FlutterDriver@8df0 (1d24424c)]     at scrollUntilVisible (/Users/han.xiao/.appium/node_modules/appium-flutter-driver/lib/commands/execute/scroll.ts:107:17)
[debug] [FlutterDriver@8df0 (1d24424c)]     at FlutterDriver.execute (/Users/han.xiao/.appium/node_modules/appium-flutter-driver/lib/commands/execute.ts:56:32)
[debug] [FlutterDriver@8df0 (1d24424c)]     at commandExecutor (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:122:18)
[debug] [FlutterDriver@8df0 (1d24424c)]     at /opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:171:12
[debug] [FlutterDriver@8df0 (1d24424c)]     at AsyncLock._promiseTry (/opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:304:31)
[debug] [FlutterDriver@8df0 (1d24424c)]     at exec (/opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:170:9)
[debug] [FlutterDriver@8df0 (1d24424c)]     at AsyncLock.acquire (/opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:187:3)
[debug] [FlutterDriver@8df0 (1d24424c)]     at FlutterDriver.executeCommand (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:138:39)
[debug] [FlutterDriver@8df0 (1d24424c)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [FlutterDriver@8df0 (1d24424c)]     at FlutterDriver.executeCommand (/Users/han.xiao/.appium/node_modules/appium-flutter-driver/lib/driver.ts:139:16)
[debug] [FlutterDriver@8df0 (1d24424c)]     at defaultBehavior (/opt/homebrew/lib/node_modules/appium/lib/appium.js:673:14)
[debug] [FlutterDriver@8df0 (1d24424c)]     at AppiumDriver.executeWrappedCommand (/opt/homebrew/lib/node_modules/appium/lib/appium.js:763:16)
[debug] [FlutterDriver@8df0 (1d24424c)]     at AppiumDriver.executeCommand (/opt/homebrew/lib/node_modules/appium/lib/appium.js:685:17)
[debug] [FlutterDriver@8df0 (1d24424c)]     at asyncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:387:19)
[HTTP] <-- POST /wd/hub/session/1d24424c-480c-4aed-af72-429e906347f4/execute/sync 500 153 ms - 860
[HTTP] 
[HTTP] --> GET /wd/hub/session/1d24424c-480c-4aed-af72-429e906347f4/screenshot
==============================

**Comment by wsfcsk** [comment]
HI
it's my mistake , i used element for the finder as parameters , i changed it to finder ,scrolling function is working 

thanks !
