### ISSUE TITLE
((SupportsContextSwitching) driver).context("FLUTTER") is not working.

### ISSUE THREAD

**Issue by pothurajtharun** [appium-userland/appium-flutter-driver#462]
When the automationName=UiAutomator2, the user is not able to switch the context to Flutter with the below configurations.

java-client: 8.2.0 
selenium: 4.5.0
Java: temurin-11.jdk
Mobile Used: Google Pixel 7 Pro
Android Version: 13.0

Here is the error stack trace :

`May 14, 2023 12:58:51 PM org.openqa.selenium.remote.ErrorCodes toStatus
INFO: HTTP Status: '400' -> incorrect JSON status mapping for 'unknown error' (500 expected)

io.appium.java_client.NoSuchContextException: No such context found.
Build info: version: '4.5.0', revision: 'fe167b119a'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.6.3', java.version: '11.0.19'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [9a7fb09f-3d41-4557-8989-a91b24b096cc, switchToContext {name=FLUTTER}]
Capabilities {appium:app: /Users/****/Docum..., appium:appPackage: com.example.flutter_auto_demo, appium:automationName: UiAutomator2, appium:databaseEnabled: false, appium:desired: {app: /Users/****/Docum..., automationName: UiAutomator2, deviceName: Google Pixel 7 Pro, noReset: true, platformName: android}, appium:deviceApiLevel: 33, appium:deviceManufacturer: Google, appium:deviceModel: Pixel 7 Pro, appium:deviceName: 2*******V, appium:deviceScreenDensity: 420, appium:deviceScreenSize: 1080x2340, appium:deviceUDID: 2*******V, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:networkConnectionEnabled: true, appium:noReset: true, appium:pixelRatio: 2.625, appium:platformVersion: 13, appium:statBarHeight: 144, appium:takesScreenshot: true, appium:viewportRect: {height: 2025, left: 0, top: 144, width: 1080}, appium:warnings: {}, appium:webStorageEnabled: false, platformName: ANDROID}
Session ID: 9a7fb09f-3d41-4557-8989-a91b24b096cc`

`at io.appium.java_client.remote.SupportsContextSwitching.context(SupportsContextSwitching.java:48)
	at com.wdc.qa.clients.flutter.tests.FlutterTest.basicTest(FlutterTest.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:829)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
	at org.testng.SuiteRunner.run(SuiteRunner.java:330)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
	at org.testng.TestNG.runSuites(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1067)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)`
	
Caused by: org.openqa.selenium.WebDriverException: No such context found.
Build info: version: '4.5.0', revision: 'fe167b119a'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.6.3', java.version: '11.0.19'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [9a7fb09f-3d41-4557-8989-a91b24b096cc, switchToContext {name=FLUTTER}]
Capabilities {appium:app: /Users/*****/Docum..., appium:appPackage: com.example.flutter_auto_demo, appium:automationName: UiAutomator2, appium:databaseEnabled: false, appium:desired: {app: /Users/******/Docum..., automationName: UiAutomator2, deviceName: Google Pixel 7 Pro, noReset: true, platformName: android}, appium:deviceApiLevel: 33, appium:deviceManufacturer: Google, appium:deviceModel: Pixel 7 Pro, appium:deviceName: 2********V, appium:deviceScreenDensity: 420, appium:deviceScreenSize: 1080x2340, appium:deviceUDID: 2*******V, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:networkConnectionEnabled: true, appium:noReset: true, appium:pixelRatio: 2.625, appium:platformVersion: 13, appium:statBarHeight: 144, appium:takesScreenshot: true, appium:viewportRect: {height: 2025, left: 0, top: 144, width: 1080}, appium:warnings: {}, appium:webStorageEnabled: false, platformName: ANDROID}
Session ID: 9a7fb09f-3d41-4557-8989-a91b24b096cc
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:189)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:267)
	at io.appium.java_client.remote.SupportsContextSwitching.context(SupportsContextSwitching.java:45)
	... 28 more`

**Comment by KazuCocoa** [comment]
> When the automationName=UiAutomator2, the user is not able to switch the context to Flutter with the below configurations.


It is expected. As https://github.com/appium-userland/appium-flutter-driver#example, the automationName should be Flutter to use this driver. UIA2 automation name uses appium-uiautomator2-driver only.
