### ISSUE TITLE
"flutter:waitFor" is not working in Java test framework

### ISSUE THREAD

**Issue by denysord88** [appium-userland/appium-flutter-driver#477]
I'm automating testing of the Flutter application by my Java test framework based on appium-flutter-driver.
I have a button with text "ACCEDI" and once the text label was changed due to a bug, my test framework was not able to find it.
I used a command `new FlutterFinder(driver).byText("ACCEDI");` and expected to have something like element not found, but Appium just wait infinitely.

To solve the infinite wait I tried to use command:
`driver.executeScript("flutter:waitFor", finder.byText("ACCEDI"), 10000);`
But I can't execute it because of an error:
`An unknown server-side error occurred while processing the command. Original error: input is invalid {"element-6066-11e4-a52e-4f735466cecf":"eyJ0ZXh0IjoiQUNDRURJIiwiZmluZGVyVHlwZSI6IkJ5VGV4dCJ9"}`
The button was there but Appium doesn't want to handle it with flutter:waitFor

Here is my code example:
```
package org.example;

import io.appium.java_client.ios.IOSDriver;
import io.appium.java_client.remote.MobileCapabilityType;
import io.appium.java_client.service.local.AppiumDriverLocalService;
import io.appium.java_client.service.local.AppiumServiceBuilder;
import io.appium.java_client.service.local.flags.GeneralServerFlag;
import io.github.ashwith.flutter.FlutterFinder;
import org.openqa.selenium.remote.DesiredCapabilities;

public class Main {
    public static void main(String[] args) {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 14 Pro Max");
        capabilities.setCapability(MobileCapabilityType.APP, "/Users/username/src/FE/...NDA:).../build/ios/iphonesimulator/Runner.app");
        capabilities.setCapability("automationName", "FLUTTER");

        AppiumDriverLocalService service = AppiumDriverLocalService.
                buildService(new AppiumServiceBuilder()
                        .usingPort(4212)
                        .withArgument(GeneralServerFlag.BASEPATH, "/wd/hub/")
                        .withArgument(() -> "--allow-insecure", "get_server_logs")
                        .withArgument(() -> "--log-level", false ? "debug" : "error"));
        service.start();

        IOSDriver driver = new IOSDriver(service.getUrl(), capabilities);
        FlutterFinder finder = new FlutterFinder(driver);
        String elementId = (String) driver.executeScript("flutter:waitFor", finder.byText("ACCEDI"), 10000);
        driver.executeScript("flutter:tap", "finder", "element", elementId);
        driver.quit();
    }
}

```

For FlutterFinder I'm using this repo in my Maven pom.xml https://github.com/ashwithpoojary98/javaflutterfinder/tree/master
```
<dependency>
    <groupId>io.github.ashwithpoojary98</groupId>
    <artifactId>appium_flutterfinder_java</artifactId>
    <version>1.0.0</version>
</dependency>
```

flutter --version
```
Flutter 3.3.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision eb6d86ee27 (8 months ago) • 2022-10-04 22:31:45 -0700
Engine • revision c08d7d5efc
Tools • Dart 2.18.2 • DevTools 2.15.0
```

appium driver list --installed
```
✔ Listing installed drivers
- flutter@1.14.3 [installed (npm)]
```

appium --version
`2.0.0-beta.63`

How to run commands like `driver.executeScript("flutter:...` in Java ??

**Comment by KazuCocoa** [comment]
I thought it worked like https://github.com/appium-userland/appium-flutter-driver/blob/e532a42bb82eb9ebf1d53b100fa384f69e32fb27/example/java/src/test/java/example/appium/FlutterTest.java#L126

Could you share the appium server log as well?

**Comment by denysord88** [comment]
I'm using <appium.java-client.version>8.5.0</appium.java-client.version>
So I replaced MobileElement with WebElement
But For this part of code I still can't execute a command
```
        FlutterFinder finder = new FlutterFinder(driver);
        WebElement element = (WebElement) driver.executeScript("flutter:waitFor", finder.byText("ACCEDI"), 10000);
        element.click();
```

Error:
`Exception in thread "main" org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: input is invalid {"element-6066-11e4-a52e-4f735466cecf":"eyJ0ZXh0IjoiQUNDRURJIiwiZmluZGVyVHlwZSI6IkJ5VGV4dCJ9"}`

Logs:
```
[debug] [XCUITest] The app has been installed successfully.
[debug] [XCUITestDriver@1311 (5b5aca76)] Event 'appInstalled' logged at 1686556466919 (10:54:26 GMT+0300 (Eastern European Summer Time))
[debug] [XCUITestDriver@1311 (5b5aca76)] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[DevCon Factory] Requesting connection for device D80B782E-78AF-47D0-8C6A-6E8171BEA050 on local port 8100
[debug] [DevCon Factory] Cached connections count: 0
[DevCon Factory] Successfully requested the connection for D80B782E-78AF-47D0-8C6A-6E8171BEA050:8100
[debug] [XCUITestDriver@1311 (5b5aca76)] Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [WD Proxy] Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"testmanagerdVersion":28,"name":"iOS","sdkVersion":"16.1","version":"16.2"},"ios":{"simulatorVersion":"16.2","ip":"192.168.88.16"},"ready":true,"build":{"upgradedAt":"1681766598615","time":"Apr 18 2023 00:24:27","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"}},"sessionId":"734B3042-AE8C-4859-9C6E-289C57D02833"}
[debug] [XCUITestDriver@1311 (5b5aca76)] Upgrade timestamp of the currently bundled WDA: 1681766598615
[debug] [XCUITestDriver@1311 (5b5aca76)] Upgrade timestamp of the WDA on the device: 1681766598615
[XCUITestDriver@1311 (5b5aca76)] Will reuse previously cached WDA instance at 'http://127.0.0.1:8100/' with 'com.facebook.WebDriverAgentRunner'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[debug] [XCUITestDriver@1311 (5b5aca76)] Trying to start WebDriverAgent 2 times with 10000ms interval
[debug] [XCUITestDriver@1311 (5b5aca76)] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[debug] [XCUITestDriver@1311 (5b5aca76)] Event 'wdaStartAttempted' logged at 1686556467007 (10:54:27 GMT+0300 (Eastern European Summer Time))
[XCUITestDriver@1311 (5b5aca76)] Using provided WebdriverAgent at 'http://127.0.0.1:8100/'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [WD Proxy] Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"testmanagerdVersion":28,"name":"iOS","sdkVersion":"16.1","version":"16.2"},"ios":{"simulatorVersion":"16.2","ip":"192.168.88.16"},"ready":true,"build":{"upgradedAt":"1681766598615","time":"Apr 18 2023 00:24:27","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"}},"sessionId":"734B3042-AE8C-4859-9C6E-289C57D02833"}
[debug] [XCUITestDriver@1311 (5b5aca76)] Event 'wdaSessionAttempted' logged at 1686556467011 (10:54:27 GMT+0300 (Eastern European Summer Time))
[debug] [XCUITestDriver@1311 (5b5aca76)] Sending createSession command to WDA
[debug] [XCUITestDriver@1311 (5b5aca76)] Matched '/session' to command name 'createSession'
[debug] [XCUITestDriver@1311 (5b5aca76)] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"...","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true,"shouldTerminateApp":true,"forceAppLaunch":true,"useNativeCachingStrategy":true,"forceSimulatorSoftwareKeyboardPresence":true}],"alwaysMatch":{}}}
[debug] [XCUITestDriver@1311 (5b5aca76)] Got response with status 200: {"value":{"sessionId":"73F79B65-6099-442B-9AEC-3CC118B6A466","capabilities":{"device":"iphone","browserName":"...","sdkVersion":"16.2","CFBundleIdentifier":"..."}},"sessionId":"73F79B65-6099-442B-9AEC-3CC118B6A466"}
[XCUITestDriver@1311 (5b5aca76)] Determined the downstream protocol as 'W3C'
[debug] [XCUITestDriver@1311 (5b5aca76)] Event 'wdaSessionStarted' logged at 1686556473022 (10:54:33 GMT+0300 (Eastern European Summer Time))
[debug] [XCUITestDriver@1311 (5b5aca76)] Event 'wdaStarted' logged at 1686556473022 (10:54:33 GMT+0300 (Eastern European Summer Time))
[debug] [BaseDriver] The value of 'elementResponseAttributes' setting did not change. Skipping the update for it
[debug] [BaseDriver] The value of 'shouldUseCompactResponses' setting did not change. Skipping the update for it
[FlutterDriver] Attempt #1
[FlutterDriver] Running on iOS simulator
[FlutterDriver] Connecting to Dart Observatory: ws://127.0.0.1:57110/r2DhlVwa5lg=/ws
[FlutterDriver] Connecting to ws://127.0.0.1:57110/r2DhlVwa5lg=/ws
[FlutterDriver] Listing all isolates: [{"type":"@Isolate","id":"isolates/3979410006108859","name":"main","number":"3979410006108859","isSystemIsolate":false}]
[AppiumDriver@ea98] New FlutterDriver session created successfully, session 63987b3f-d218-4742-807a-7394e5a73d3a added to master session list
[debug] [AppiumDriver@ea98] Event 'newSessionStarted' logged at 1686556473081 (10:54:33 GMT+0300 (Eastern European Summer Time))
[debug] [FlutterDriver@9bb7 (63987b3f)] Cached the protocol value 'W3C' for the new session 63987b3f-d218-4742-807a-7394e5a73d3a
[debug] [FlutterDriver@9bb7 (63987b3f)] Responding to client with driver.createSession() result: {"capabilities":{"subcommand":"server","address":"0.0.0.0","allowInsecure":["get_server_logs"],"basePath":"/wd/hub/","loglevel":"debug","port":4214,"extraArgs":[],"allowCors":false,"callbackPort":4723,"debugLogSpacing":false,"denyInsecure":[],"keepAliveTimeout":600,"localTimezone":false,"logNoColors":false,"logTimestamp":false,"longStacktrace":false,"noPermsCheck":false,"relaxedSecurityEnabled":false,"sessionOverride":false,"strictCaps":false,"useDrivers":[],"usePlugins":[],"tmpDir":"/var/folders/3r/ngmg2cws4_74s78r_sdbzyv80000gn/T","platformName":"IOS","app":".../Runner.app","automationName":"FLUTTER","deviceName":"iPhone 14 Pro Max","fastReset":true,"skipUninstall":true}}
[HTTP] <-- POST /wd/hub/session 200 15193 ms - 836
[HTTP] 
[HTTP] --> POST /wd/hub/session/63987b3f-d218-4742-807a-7394e5a73d3a/execute/sync
[HTTP] {"script":"flutter:waitFor","args":[{"element-6066-11e4-a52e-4f735466cecf":"eyJ0ZXh0IjoiQUNDRURJIiwiZmluZGVyVHlwZSI6IkJ5VGV4dCJ9"},10000]}
[debug] [FlutterDriver@9bb7 (63987b3f)] Calling AppiumDriver.execute() with args: ["flutter:waitFor",[{"element-6066-11e4-a52e-4f735466cecf":"eyJ0ZXh0IjoiQUNDRURJIiwiZmluZGVyVHlwZSI6IkJ5VGV4dCJ9"},10000],"63987b3f-d218-4742-807a-7394e5a73d3a"]
[debug] [FlutterDriver] Executing Flutter driver command 'execute'
[debug] [FlutterDriver@9bb7 (63987b3f)] Encountered internal error running command: Error: input is invalid {"element-6066-11e4-a52e-4f735466cecf":"eyJ0ZXh0IjoiQUNDRURJIiwiZmluZGVyVHlwZSI6IkJ5VGV4dCJ9"}
[debug] [FlutterDriver@9bb7 (63987b3f)]     at decode (/Users/username/.appium/node_modules/appium-flutter-driver/lib/sessions/base64url.ts:8:11)
[debug] [FlutterDriver@9bb7 (63987b3f)]     at FlutterDriver.executeElementCommand (/Users/username/.appium/node_modules/appium-flutter-driver/lib/sessions/observatory.ts:170:58)
[debug] [FlutterDriver@9bb7 (63987b3f)]     at /Users/username/.appium/node_modules/appium-flutter-driver/lib/commands/execute/wait.ts:20:14
[debug] [FlutterDriver@9bb7 (63987b3f)]     at FlutterDriver.execute (/Users/username/.appium/node_modules/appium-flutter-driver/lib/commands/execute.ts:50:21)
[debug] [FlutterDriver@9bb7 (63987b3f)]     at commandExecutor (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:106:18)
[debug] [FlutterDriver@9bb7 (63987b3f)]     at /usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:171:12
[debug] [FlutterDriver@9bb7 (63987b3f)]     at AsyncLock._promiseTry (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:304:31)
[debug] [FlutterDriver@9bb7 (63987b3f)]     at exec (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:170:9)
[debug] [FlutterDriver@9bb7 (63987b3f)]     at AsyncLock.acquire (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:187:3)
[debug] [FlutterDriver@9bb7 (63987b3f)]     at FlutterDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:122:39)
[debug] [FlutterDriver@9bb7 (63987b3f)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [FlutterDriver@9bb7 (63987b3f)]     at FlutterDriver.executeCommand (/Users/username/.appium/node_modules/appium-flutter-driver/lib/driver.ts:167:16)
[debug] [FlutterDriver@9bb7 (63987b3f)]     at defaultBehavior (/usr/local/lib/node_modules/appium/lib/appium.js:684:14)
[debug] [FlutterDriver@9bb7 (63987b3f)]     at AppiumDriver.executeWrappedCommand (/usr/local/lib/node_modules/appium/lib/appium.js:774:16)
[debug] [FlutterDriver@9bb7 (63987b3f)]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:696:17)
[debug] [FlutterDriver@9bb7 (63987b3f)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:387:19)
[HTTP] <-- POST /wd/hub/session/63987b3f-d218-4742-807a-7394e5a73d3a/execute/sync 500 35 ms - 730
[HTTP] 
Exception in thread "main" org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: input is invalid {"element-6066-11e4-a52e-4f735466cecf":"eyJ0ZXh0IjoiQUNDRURJIiwiZmluZGVyVHlwZSI6IkJ5VGV4dCJ9"}
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.4', java.version: '19.0.1'
Driver info: io.appium.java_client.ios.IOSDriver
Command: [63987b3f-d218-4742-807a-7394e5a73d3a, executeScript {script=flutter:waitFor, args=[{element-6066-11e4-a52e-4f735466cecf=eyJ0ZXh0IjoiQUNDRURJIiwiZmluZGVyVHlwZSI6IkJ5VGV4dCJ9}, 10000]}]
Capabilities {appium:address: 0.0.0.0, appium:allowCors: false, appium:allowInsecure: [get_server_logs], appium:app: /Users/username/src/FE/sr..., appium:automationName: FLUTTER, appium:basePath: /wd/hub/, appium:callbackPort: 4723, appium:debugLogSpacing: false, appium:denyInsecure: [], appium:deviceName: iPhone 14 Pro Max, appium:extraArgs: [], appium:fastReset: true, appium:keepAliveTimeout: 600, appium:localTimezone: false, appium:logNoColors: false, appium:logTimestamp: false, appium:loglevel: debug, appium:longStacktrace: false, appium:noPermsCheck: false, appium:port: 4214, appium:relaxedSecurityEnabled: false, appium:sessionOverride: false, appium:skipUninstall: true, appium:strictCaps: false, appium:subcommand: server, appium:tmpDir: /var/folders/3r/ngmg2cws4_7..., appium:useDrivers: [], appium:usePlugins: [], platformName: IOS}
Session ID: 63987b3f-d218-4742-807a-7394e5a73d3a
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:193)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:480)
	at org.example.Main.main(Main.java:30)
Disconnected from the target VM, address: '127.0.0.1:57084', transport: 'socket'

Process finished with exit code 1

```

**Comment by ahmer-hash** [comment]
Hi @KazuCocoa 
Did you get a chance to look at the above issue?

**Comment by thuonglai** [comment]
I am using 
(RemoteWebElement) androidDriver().executeScript("flutter:waitFor", element, timeoutMilliseconds); 
And it still working

**Comment by denysord88** [comment]
```
        System.out.println("1 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
        RemoteWebElement cancel = (RemoteWebElement) ((IOSDriver)getAppiumInstance().getDriver()).executeScript("flutter:waitFor", new FlutterFinder(getAppiumInstance().getDriver()).byText("CANCEL"), 30000);
        System.out.println("2 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
```

```
1 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[HTTP] --> POST /wd/hub/session/ac3539f8-c455-4872-b2fe-384a804d81e6/execute/sync
[HTTP] {"script":"flutter:waitFor","args":[{"element-6066-11e4-a52e-4f735466cecf":"eyJ0ZXh0IjoiQ0FOQ0VMIiwiZmluZGVyVHlwZSI6IkJ5VGV4dCJ9"},30000]}
[debug] [FlutterDriver@68fe (ac3539f8)] Calling AppiumDriver.execute() with args: ["flutter:waitFor",[{"element-6066-11e4-a52e-4f735466cecf":"eyJ0ZXh0IjoiQ0FOQ0VMIiwiZmluZGVyVHlwZSI6IkJ5VGV4dCJ9"},30000],"ac3539f8-c455-4872-b2fe-384a804d81e6"]
[debug] [FlutterDriver] Executing Flutter driver command 'execute'
[debug] [FlutterDriver@68fe (ac3539f8)] Encountered internal error running command: Error: input is invalid {"element-6066-11e4-a52e-4f735466cecf":"eyJ0ZXh0IjoiQ0FOQ0VMIiwiZmluZGVyVHlwZSI6IkJ5VGV4dCJ9"}
[debug] [FlutterDriver@68fe (ac3539f8)]     at decode (/Users/denysord88/.appium/node_modules/appium-flutter-driver/lib/sessions/base64url.ts:8:11)
[debug] [FlutterDriver@68fe (ac3539f8)]     at FlutterDriver.executeElementCommand (/Users/denysord88/.appium/node_modules/appium-flutter-driver/lib/sessions/observatory.ts:170:58)
[debug] [FlutterDriver@68fe (ac3539f8)]     at /Users/denysord88/.appium/node_modules/appium-flutter-driver/lib/commands/execute/wait.ts:20:14
[debug] [FlutterDriver@68fe (ac3539f8)]     at FlutterDriver.execute (/Users/denysord88/.appium/node_modules/appium-flutter-driver/lib/commands/execute.ts:50:21)
[debug] [FlutterDriver@68fe (ac3539f8)]     at commandExecutor (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:107:18)
[debug] [FlutterDriver@68fe (ac3539f8)]     at /usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:171:12
[debug] [FlutterDriver@68fe (ac3539f8)]     at AsyncLock._promiseTry (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:304:31)
[debug] [FlutterDriver@68fe (ac3539f8)]     at exec (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:170:9)
[debug] [FlutterDriver@68fe (ac3539f8)]     at AsyncLock.acquire (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:187:3)
[debug] [FlutterDriver@68fe (ac3539f8)]     at FlutterDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:123:39)
[debug] [FlutterDriver@68fe (ac3539f8)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [FlutterDriver@68fe (ac3539f8)]     at FlutterDriver.executeCommand (/Users/denysord88/.appium/node_modules/appium-flutter-driver/lib/driver.ts:167:16)
[debug] [FlutterDriver@68fe (ac3539f8)]     at defaultBehavior (/usr/local/lib/node_modules/appium/lib/appium.js:684:14)
[debug] [FlutterDriver@68fe (ac3539f8)]     at AppiumDriver.executeWrappedCommand (/usr/local/lib/node_modules/appium/lib/appium.js:774:16)
[debug] [FlutterDriver@68fe (ac3539f8)]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:696:17)
[debug] [FlutterDriver@68fe (ac3539f8)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:393:19)
[HTTP] <-- POST /wd/hub/session/ac3539f8-c455-4872-b2fe-384a804d81e6/execute/sync 500 17 ms - 730
```

**Comment by thuonglai** [comment]
My log :
`[HTTP] --> POST /wd/hub/session/10314b71-4593-4458-8af8-62ac16d98aa6/execute/sync
[HTTP] {"script":"flutter:waitFor","args":[{"ELEMENT":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoidGV4dF9maWVsZF9jb2RlIn0","element-6066-11e4-a52e-4f735466cecf":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoidGV4dF9maWVsZF9jb2RlIn0"},60000]}
[debug] [FlutterDriver@86c4 (10314b71)] Calling AppiumDriver.execute() with args: ["flutter:waitFor",[{"ELEMENT":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoidGV4dF9maWVsZF9jb2RlIn0","element-6066-11e4-a52e-4f735466cecf":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoidGV4dF9maWVsZF9jb2RlIn0"},60000],"10314b71-4593-4458-8af8-62ac16d98aa6"]
[debug] [FlutterDriver] Executing Flutter driver command 'execute'
[debug] [FlutterDriver] >>> {"command":"waitFor","finderType":"ByValueKey","keyValueType":"String","keyValueString":"text_field_code","timeout":60000}
[debug] [FlutterDriver] <<< {"isError":false,"response":{},"type":"_extensionType","method":"ext.flutter.driver"} | previous command waitFor
[debug] [FlutterDriver@86c4 (10314b71)] Responding to client with driver.execute() result: {"element-6066-11e4-a52e-4f735466cecf":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoidGV4dF9maWVsZF9jb2RlIn0","ELEMENT":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoidGV4dF9maWVsZF9jb2RlIn0"}
[HTTP] <-- POST /wd/hub/session/10314b71-4593-4458-8af8-62ac16d98aa6/execute/sync 200 219 ms - 295`

**Comment by thuonglai** [comment]
My log 
```
1 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[HTTP] --> POST /wd/hub/session/ac3539f8-c455-4872-b2fe-384a804d81e6/execute/sync
[HTTP] {"script":"flutter:waitFor","args":[{"element-6066-11e4-a52e-4f735466cecf":"eyJ0ZXh0IjoiQ0FOQ0VMIiwiZmluZGVyVHlwZSI6IkJ5VGV4dCJ9"},30000]}
[debug] [FlutterDriver@68fe (ac3539f8)] Calling AppiumDriver.execute() with args: ["flutter:waitFor",[{"element-6066-11e4-a52e-4f735466cecf":"eyJ0ZXh0IjoiQ0FOQ0VMIiwiZmluZGVyVHlwZSI6IkJ5VGV4dCJ9"},30000],"ac3539f8-c455-4872-b2fe-384a804d81e6"]
[debug] [FlutterDriver] Executing Flutter driver command 'execute'
[debug] [FlutterDriver@68fe (ac3539f8)] Encountered internal error running command: Error: input is invalid {"element-6066-11e4-a52e-4f735466cecf":"eyJ0ZXh0IjoiQ0FOQ0VMIiwiZmluZGVyVHlwZSI6IkJ5VGV4dCJ9"}
[debug] [FlutterDriver@68fe (ac3539f8)]     at decode (/Users/denysord88/.appium/node_modules/appium-flutter-driver/lib/sessions/base64url.ts:8:11)
[debug] [FlutterDriver@68fe (ac3539f8)]     at FlutterDriver.executeElementCommand (/Users/denysord88/.appium/node_modules/appium-flutter-driver/lib/sessions/observatory.ts:170:58)
[debug] [FlutterDriver@68fe (ac3539f8)]     at /Users/denysord88/.appium/node_modules/appium-flutter-driver/lib/commands/execute/wait.ts:20:14
[debug] [FlutterDriver@68fe (ac3539f8)]     at FlutterDriver.execute (/Users/denysord88/.appium/node_modules/appium-flutter-driver/lib/commands/execute.ts:50:21)
[debug] [FlutterDriver@68fe (ac3539f8)]     at commandExecutor (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:107:18)
[debug] [FlutterDriver@68fe (ac3539f8)]     at /usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:171:12
[debug] [FlutterDriver@68fe (ac3539f8)]     at AsyncLock._promiseTry (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:304:31)
[debug] [FlutterDriver@68fe (ac3539f8)]     at exec (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:170:9)
[debug] [FlutterDriver@68fe (ac3539f8)]     at AsyncLock.acquire (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:187:3)
[debug] [FlutterDriver@68fe (ac3539f8)]     at FlutterDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:123:39)
[debug] [FlutterDriver@68fe (ac3539f8)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [FlutterDriver@68fe (ac3539f8)]     at FlutterDriver.executeCommand (/Users/denysord88/.appium/node_modules/appium-flutter-driver/lib/driver.ts:167:16)
[debug] [FlutterDriver@68fe (ac3539f8)]     at defaultBehavior (/usr/local/lib/node_modules/appium/lib/appium.js:684:14)
[debug] [FlutterDriver@68fe (ac3539f8)]     at AppiumDriver.executeWrappedCommand (/usr/local/lib/node_modules/appium/lib/appium.js:774:16)
[debug] [FlutterDriver@68fe (ac3539f8)]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:696:17)
[debug] [FlutterDriver@68fe (ac3539f8)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:393:19)
[HTTP] <-- POST /wd/hub/session/ac3539f8-c455-4872-b2fe-384a804d81e6/execute/sync 500 17 ms - 730
```

**Comment by KazuCocoa** [comment]
What version of appium flutter driver did you use? @denysord88 
https://github.com/appium-userland/appium-flutter-driver/issues/477#issuecomment-1669138849

Perhaps it was https://github.com/appium-userland/appium-flutter-driver/issues/463. https://github.com/appium-userland/appium-flutter-driver/pull/467 might fix it.

**Comment by denysord88** [comment]
> What version of appium flutter driver did you use? @denysord88 [#477 (comment)](https://github.com/appium-userland/appium-flutter-driver/issues/477#issuecomment-1669138849)
> 
> Perhaps it was #463. #467 might fix it.

I'm using v1.14.3

**Comment by denysord88** [comment]
Looks like the latest one is 1.19.1 https://www.npmjs.com/package/appium-flutter-driver
I will try it tomorrow

**Comment by denysord88** [comment]
Working fine on appium-flutter-driver v1.19.1
Thanks!
