### ISSUE TITLE
Unable to start session due to Appium Server errors

### ISSUE THREAD

**Issue by alessandro-violante** [appium-userland/appium-flutter-driver#479]
Hi,

I'm writing you because I would like to try this library with my application written in Flutter. 

Actually, after having established the connection to the Appium Server using the following command:
```appium -a 127.0.0.1 -p 4723 --allow-cors --session-override```

I've tried to run the Appium Inspector with the following configuration:

![flutter-desired-capabilities](https://github.com/appium-userland/appium-flutter-driver/assets/25792930/eb90f168-f38b-4d78-8f7e-4dafa06f93bf)

The application doesn't open, and in the Appium Server I see the following logs:

```
New FlutterDriver session created successfully, session 16faeda2-1e6f-4d98-ac35-ba03a6471c0b added to master session list
[debug] [AppiumDriver@7e1a] Event 'newSessionStarted' logged at 1686738910038 (12:35:10 GMT+0200 (Ora legale dell’Europa centrale))
[AppiumDriver@7e1a] Promoting 1 sessionless plugins to be attached to session ID 16faeda2-1e6f-4d98-ac35-ba03a6471c0b
[debug] [FlutterDriver@a2f4 (16faeda2)] Cached the protocol value 'W3C' for the new session 16faeda2-1e6f-4d98-ac35-ba03a6471c0b
[debug] [FlutterDriver@a2f4 (16faeda2)] Responding to client with driver.createSession() result: {"capabilities":{"subcommand":"server","address":"127.0.0.1","allowCors":true,"port":4723,"sessionOverride":true,"usePlugins":["execute-driver"],"extraArgs":[],"allowInsecure":[],"basePath":"","callbackPort":4723,"debugLogSpacing":false,"denyInsecure":[],"keepAliveTimeout":600,"localTimezone":false,"loglevel":"debug","logNoColors":false,"logTimestamp":false,"longStacktrace":false,"noPermsCheck":false,"relaxedSecurityEnabled":false,"strictCaps":false,"useDrivers":[],"tmpDir":"C:\\Users\\endrim\\AppData\\Local\\Temp","platformName":"Android","platformVersion":"13","deviceName":"R9JRC0EL0YT","automationName":"Flutter","ensureWebviewsHavePages":true,"nativeWebScreenshot":true,"newCommandTimeout":3600,"connectHardwareKeyboard":true,"fastReset":true,"skipUninstall":true}}
[HTTP] <-- POST /session 200 6550 ms - 837
[HTTP]
[HTTP] --> GET /session/16faeda2-1e6f-4d98-ac35-ba03a6471c0b/screenshot
[HTTP] {}
[debug] [FlutterDriver@a2f4 (16faeda2)] Calling AppiumDriver.getScreenshot() with args: ["16faeda2-1e6f-4d98-ac35-ba03a6471c0b"]
[debug] [FlutterDriver] Executing Flutter driver command 'getScreenshot'
[debug] [FlutterDriver@a2f4 (16faeda2)] Encountered internal error running command: TypeError: Cannot read properties of null (reading 'call')
[debug] [FlutterDriver@a2f4 (16faeda2)]     at FlutterDriver.getScreenshot (C:\Users\endrim\.appium\node_modules\appium-flutter-driver\lib\commands\screen.ts:4:39)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at commandExecutor (C:\Users\endrim\AppData\R1oaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\driver.ts:106:18)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at C:\Users\endrim\AppData\Roaming\npm\node_modules\appium\node_modules\async-lock\lib\index.js:171:12
[debug] [FlutterDriver@a2f4 (16faeda2)]     at AsyncLock._promiseTry (C:\Users\endrim\AppData\Roaming\npm\node_modules\appium\node_modules\async-lock\lib\index.js:304:31)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at exec (C:\Users\endrim\AppData\Roaming\npm\node_modules\appium\node_modules\async-lock\lib\index.js:170:9)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at AsyncLock.acquire (C:\Users\endrim\AppData\Roaming\npm\node_modules\appium\node_modules\async-lock\lib\index.js:187:3)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at FlutterDriver.executeCommand (C:\Users\endrim\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\driver.ts:122:39)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at FlutterDriver.executeCommand (C:\Users\endrim\.appium\node_modules\appium-flutter-driver\lib\driver.ts:167:16)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at defaultBehavior (C:\Users\endrim\AppData\Roaming\npm\node_modules\appium\lib\appium.js:684:14)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at AppiumDriver.executeWrappedCommand (C:\Users\endrim\AppData\Roaming\npm\node_modules\appium\lib\appium.js:774:16)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at AppiumDriver.executeCommand (C:\Users\endrim\AppData\Roaming\npm\node_modules\appium\lib\appium.js:696:17)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at asyncHandler (C:\Users\endrim\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:393:19)
[HTTP] <-- GET /session/16faeda2-1e6f-4d98-ac35-ba03a6471c0b/screenshot 500 54 ms - 662
[HTTP]
[HTTP] --> GET /session/16faeda2-1e6f-4d98-ac35-ba03a6471c0b/window/rect
[HTTP] {}
[debug] [FlutterDriver@a2f4 (16faeda2)] Calling AppiumDriver.getWindowRect() with args: ["16faeda2-1e6f-4d98-ac35-ba03a6471c0b"]
[debug] [FlutterDriver] Executing Flutter driver command 'getWindowRect'
[debug] [FlutterDriver@a2f4 (16faeda2)] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
[debug] [FlutterDriver@a2f4 (16faeda2)]     at FlutterDriver.executeCommand (C:\Users\endrim\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\driver.ts:100:13)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at FlutterDriver.executeCommand (C:\Users\endrim\.appium\node_modules\appium-flutter-driver\lib\driver.ts:167:16)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at defaultBehavior (C:\Users\endrim\AppData\Roaming\npm\node_modules\appium\lib\appium.js:684:14)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at AppiumDriver.executeWrappedCommand (C:\Users\endrim\AppData\Roaming\npm\node_modules\appium\lib\appium.js:774:16)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at AppiumDriver.executeCommand (C:\Users\endrim\AppData\Roaming\npm\node_modules\appium\lib\appium.js:696:17)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at asyncHandler (C:\Users\endrim\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:393:19)
[HTTP] <-- GET /session/16faeda2-1e6f-4d98-ac35-ba03a6471c0b/window/rect 405 17 ms - 1057
[HTTP]
[HTTP] --> GET /session/16faeda2-1e6f-4d98-ac35-ba03a6471c0b/source
[HTTP] {}
[debug] [FlutterDriver@a2f4 (16faeda2)] Calling AppiumDriver.getPageSource() with args: ["16faeda2-1e6f-4d98-ac35-ba03a6471c0b"]
[debug] [FlutterDriver] Executing Flutter driver command 'getPageSource'
[debug] [FlutterDriver@a2f4 (16faeda2)] Encountered internal error running command: NotImplementedError: Not implemented yet for find.
[debug] [FlutterDriver@a2f4 (16faeda2)]     at FlutterDriver.getPageSource (C:\Users\endrim\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\commands\find.ts:54:11)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at commandExecutor (C:\Users\endrim\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\driver.ts:106:18)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at C:\Users\endrim\AppData\Roaming\npm\node_modules\appium\node_modules\async-lock\lib\index.js:171:12
[debug] [FlutterDriver@a2f4 (16faeda2)]     at AsyncLock._promiseTry (C:\Users\endrim\AppData\Roaming\npm\node_modules\appium\node_modules\async-lock\lib\index.js:304:31)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at exec (C:\Users\endrim\AppData\Roaming\npm\node_modules\appium\node_modules\async-lock\lib\index.js:170:9)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at AsyncLock.acquire (C:\Users\endrim\AppData\Roaming\npm\node_modules\appium\node_modules\async-lock\lib\index.js:187:3)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at FlutterDriver.executeCommand (C:\Users\endrim\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\driver.ts:122:39)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at FlutterDriver.executeCommand (C:\Users\endrim\.appium\node_modules\appium-flutter-driver\lib\driver.ts:167:16)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at defaultBehavior (C:\Users\endrim\AppData\Roaming\npm\node_modules\appium\lib\appium.js:684:14)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at AppiumDriver.executeWrappedCommand (C:\Users\endrim\AppData\Roaming\npm\node_modules\appium\lib\appium.js:774:16)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at AppiumDriver.executeCommand (C:\Users\endrim\AppData\Roaming\npm\node_modules\appium\lib\appium.js:696:17)
[debug] [FlutterDriver@a2f4 (16faeda2)]     at asyncHandler (C:\Users\endrim\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:393:19)
[HTTP] <-- GET /session/16faeda2-1e6f-4d98-ac35-ba03a6471c0b/source 405 25 ms - 1906
[HTTP]
[HTTP] --> GET /session/16faeda2-1e6f-4d98-ac35-ba03a6471c0b/timeouts
[HTTP] {}
[debug] [FlutterDriver@a2f4 (16faeda2)] Calling AppiumDriver.getTimeouts() with args: ["16faeda2-1e6f-4d98-ac35-ba03a6471c0b"]
[debug] [FlutterDriver] Executing Flutter driver command 'getTimeouts'
[debug] [FlutterDriver@a2f4 (16faeda2)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /session/16faeda2-1e6f-4d98-ac35-ba03a6471c0b/timeouts 200 7 ms - 42 
```

I specify I have installed Appium 2.0 and the latest versions of Appium Flutter Driver and Appium Flutter Library.

I have searched for these errors on Google but I haven't find anything about them.
 
Am I missing something in my configuration? Could you help me in resolving my issue?

Thanks a lot in advance.

**Comment by KazuCocoa** [comment]
Btw, below means a new session creation itself succeeded.

```
[debug] [AppiumDriver@7e1a] Event 'newSessionStarted' logged at 1686738910038 (12:35:10 GMT+0200 (Ora legale dell’Europa centrale))
[AppiumDriver@7e1a] Promoting 1 sessionless plugins to be attached to session ID 16faeda2-1e6f-4d98-ac35-ba03a6471c0b
[debug] [FlutterDriver@a2f4 (16faeda2)] Cached the protocol value 'W3C' for the new session 16faeda2-1e6f-4d98-ac35-ba03a6471c0b
[debug] [FlutterDriver@a2f4 (16faeda2)] Responding to client with driver.createSession() result: {"capabilities":{"subcommand":"server","address":"127.0.0.1","allowCors":true,"port":4723,"sessionOverride":true,"usePlugins":["execute-driver"],"extraArgs":[],"allowInsecure":[],"basePath":"","callbackPort":4723,"debugLogSpacing":false,"denyInsecure":[],"keepAliveTimeout":600,"localTimezone":false,"loglevel":"debug","logNoColors":false,"logTimestamp":false,"longStacktrace":false,"noPermsCheck":false,"relaxedSecurityEnabled":false,"strictCaps":false,"useDrivers":[],"tmpDir":"C:\\Users\\endrim\\AppData\\Local\\Temp","platformName":"Android","platformVersion":"13","deviceName":"R9JRC0EL0YT","automationName":"Flutter","ensureWebviewsHavePages":true,"nativeWebScreenshot":true,"newCommandTimeout":3600,"connectHardwareKeyboard":true,"fastReset":true,"skipUninstall":true}}
[HTTP] <-- POST /session 200 6550 ms - 837
```

**Comment by alessandro-violante** [comment]
Hi,

Thank you, does a solution for this "problem" actually exist?

If Appium Inspector doesn't actually work with this plugin, could I use the plugin with Robot Framework simply including it in my project and using its functions, using automationName = Flutter, or isn't it compatible with Robot Framework or should I use additional configuration?

Thank you in advance.

**Comment by KazuCocoa** [comment]
I'm not sure if Robot Framework supports this driver, but Appium Python client can use this. e.g. https://github.com/appium-userland/appium-flutter-driver/blob/main/example/python/example.py

**Comment by alessandro-violante** [comment]
Hi,

Thanks for the explanation.

I've tried to execute a test with Robot Framework.

The test opens the app, then I try to use the Input Text function on an input field using its key.

In the Appium Server logs, these logs are printed:

```
[FlutterDriver] Attempt #1
[debug] [FlutterDriver] Error: No observatory url was found in the device log. Please make sure the application under test logs an observatory url when the application starts.
[debug] [FlutterDriver]     at processLogToGetobservatory (C:\Users\endrim\.appium\node_modules\appium-flutter-driver\lib\sessions\observatory.ts:197:11)
[debug] [FlutterDriver]     at getObservatoryWsUri (C:\Users\endrim\.appium\node_modules\appium-flutter-driver\lib\sessions\android.ts:62:43)
[debug] [FlutterDriver]     at connectSocket (C:\Users\endrim\.appium\node_modules\appium-flutter-driver\lib\sessions\observatory.ts:33:34)
[debug] [FlutterDriver]     at startAndroidSession (C:\Users\endrim\.appium\node_modules\appium-flutter-driver\lib\sessions\android.ts:33:18)
[debug] [FlutterDriver]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [FlutterDriver]     at FlutterDriver.createSession (C:\Users\endrim\.appium\node_modules\appium-flutter-driver\lib\sessions\session.ts:43:47)
[debug] [FlutterDriver]     at AppiumDriver.createSession (C:\Users\endrim\AppData\Roaming\npm\node_modules\appium\lib\appium.js:346:35)
[FlutterDriver] Connecting to Dart Observatory: undefined
[FlutterDriver] {}
[FlutterDriver] Check Dart Observatory URI no URI found in the device log
[FlutterDriver] Waiting 3 seconds before trying...
```

What should I do?

Maybe I should configure the "appium:observatoryWsUri" Device Capability, but how could I know which uri should I set?

Thank you in advance.

**Comment by KazuCocoa** [comment]
Did you configure https://github.com/appium-userland/appium-flutter-driver#usage ? Set  flutter_driver for the app dependency and set enableFlutterDriverExtension?

`observatoryWsUri` is for advanced usage. Usually this driver gets the url automatically, but the error means probably your app hasn't exposed the expected url because of not configured as the usage

**Comment by KazuCocoa** [comment]
What I know of is basically that's all.
Did you confirm the observatory url exist in the logcat when you launch the app? If not, maybe your DartVM hasn't been exposed. For example, a release build does not work.
